* USEFUL ARABIC – ENGLISH TRANSLATION FOR OPTOMETRIST

WORDS YOU CAN USE

FADAL – means COME INSIDE, WELCOME, GO AHEAD or PLEASE

EHSTERRE or EDGELIS– means SITDOWN

HUT – means PUT

DIGGIN – means CHIN

HENNA – means HERE

SHOUF – means SEE or LOOK

ALATOL – means STRAIGHT

KOLLO – means ALL

EYEON – means EYES

IFTA – means OPEN

LAT – means DON’T

HARAK – means MOVE

KHALAS – means FINISH

NADARA – means EYE GLASSES

KAM? – means HOW? or HOW MANY?

OMBRAK – means (old) AGE (MALE)

OMBRIK – means (old) AGE (FEMALE)

INTA – means YOU

FI – means HAVE

MAGAS – means POWER or PRESCRIPTION or SIZE

GADIM – means OLD

NADARA TOBIA – means PRESCRIPTION EYE GLASSES

NADARA SHYAMSIA – means SUNGLASSES

AIWA – means YES

LA or MO – means NO

KAM SANAH? – means HOW MANY YEARS?

ANA – means I

JADID – means NEW

MAFI – means DON’T or DON’T HAVE

MALLUNG / FAHAM – means UNDERSTAND or KNOW

MORTAH – means COMFORTABLE (MALE)

MORTAHAH – means COMFORTABLE (FEMALE)

ARABIC SENTENCES YOU CAN USE FOR EYE REFRACTION

INTA FI SHOUF? – means CAN YOU SEE?

AIY WAHAD AWDAH/AHSSAN? – means WHICH ONE IS CLEARER/GOOD?

HADI WELLA HADI? – means THIS ONE OR THIS ONE?

SHOUF SATEER AWOL – means LOOK AT THE FIRST LINE

SHOUF SATEER THANI – means LOOK AT THE SECOND LINE

SHOUF SATEER THALITH – means LOOK AT THE THIRD LINE

SHOUF SATEER RABA – means LOOK AT THE FORTH LINE

KALAM FIN FATHA? – means WHERE’S THE DIRECTION (OF THE E)

ALHIN NAFSU WELLA ASGHER? – means NOW IS IT THE SAME OR SMALLER?

SHOUF HADI BASS – means LOOK AT THIS ONLY

AIY WAHAD AWDAH YAMIN WELLA YASAR? – means WHICH ONE IS CLEARER THE RIGHT OR THE LEFT?

MONKEN EMSHI – means PLEASE WALK

SHOUF ARDT – means LOOK AT THE FLOOR

MAFI MOSHKILLA? – means NO PROBLEM?

HADAH MORTAH? – means IS THIS COMFORTABLE?

HADAH MIYA FIL MIYA? – means IS THAT ONE HUNDRED PERCENT?

ALHIN INTA MAGAS FI YATADGE – means NOW YOUR PRESCRIPTION INCREASED.

INTA ELBIS NADARA, EL AWOL MONKEN FI SUDAH/MOSHKILLA, BAADEN…TALATA YUM, ARBAA YUM. INTA FI SHOUF TAMAM. – means
THE FIRST TIME YOU WEAR, POSSIBLY YOU FEEL UNCOMFORTABLE. AFTER THREE TO FOUR DAYS, YOU WILL SEE/FEEL GOOD.

INTA LASM ELBIS NADARA – means YOU MUST WEAR EYEGLASSES

MONKEN SUAL MR….(THE SALESMAN NAME) – means PLEASE ASK MR….

AWOL MARRA – means FIRST TIME

AHSSAN – means GOOD

DI or HADI – means THIS

HADAH – means THAT

WELLA – means OR

SWAY – means A LITTLE

SWAYSWAY – means LITTLE BY LITTLE

SWAYYAH – means FOR A WHILE

NAFSHASHAY or NAFSU – means THE SAME

BAID/MASAFAH – means FAR

GARRIB/KARA A – means NEAR

JADID – means NEW

GADIM – means OLD

FOUK – means UP

THAHAD – means DOWN

YAMIN – means RIGHT

YASAR – means LEFT

ASGHER – means SMALL

SAWWI – means DO

KIDDAH – means THIS ONE or LIKE THIS

ADUA – means READ

ALHIN – means NOW

MIYA FIL MIYA – means 100 PERCENT

WAHDAH – means CLEAR

AWDAH – means CLEARER

AL AWDAH – means CLEAREST

KATHEER – means MANNY or VERY MUCH

SAGEAR – means SMALL

KHABIR – means BIG

AKBHAR – means BIGGER

AL AKBHAR – means BIGGEST

SATEER – means LINE

AWOL – means FIRST

THANI – means SECOND

THALITH – means THIRD

RHABA – means FORTH

ZA ED – means PLUS (+)

NOH ES – means MINUS (-)

ONOUS – means 0.50 (half)

RUBA – means 0.25 (quarter)

SUAL – means ASK (?)

QUAIZ – means GOOD or FINE

SUDAH or ZACKALALA – means HEADACHED

FIN – means WHERE

MAZZA – means WHAT

LESH – means WHY

MAN – means WHO

KAIF or ZAIYAK – means HOW

MATAH – means WHEN

AIY – means WHICH

WAH – means AND

MA A – means WITH

BUSS – means ONLY

MAZBOOT – means VERY WELL

CALLAM – means TALK

ILLIOM – means TODAY

KOL YUM – means EVERYDAY

KOL LAILA – means EVERY NIGHT

KOL OSBU – means EVERY WEEK

KOL SHAHR – means EVERY MONTH

KOL SANA – means EVERY YEAR

BUKRA – means TOMORROW

LASM – means MUST

MONKEN – means MAYBE, POSSIBLE or PLEASE

EMSHI – means WALK

ARDT – means FLOOR

MOYA ABYAT – means CATARACT

INHIRAF – means ASTIGMATISM

HAWAL – means CROSS EYE

KASLAN – means LAZY

MOYA ASHRAQ – means GLAUCOMA

QUESTIONS YOU MAY NEED TO ASK:

INTA FI SUKAR? – means DO YOU HAVE DIABETIS?

INTA FI DART? – means DO YOU HAVE HIGH BLOOD PRESSURE?

WORDS YOU CAN USE AND HEAR ABOUT CONTACT LENSES

SHILL – means REMOVE

FOKKHEH – means LOOK UP

ELBIS – means WEAR

MAHALOL – means CONTACT LENS SOLUTION

ELBA – means CONTACT LENS CASE

DACLE – means INSIDE

TANDIF – means CLEAN

MISSLE HAZZAH – means LIKE THIS

GATRA – means LUBRICANT

MOAKAT – means DISPOASBLE

ADASAT – means LENS

ADASAT LASKA – means CONTACT LENS

DAIMA or ALATOL – means CONVETIONAL CONTACT LENS

SHAHARIYA – means MONTHLY

ISHBUYA – means WEEKLY

YOMIYYA – means DAILLY

SALBA – means HARD LENS

YAD – means HANDS

MAYA – means WATER

HABBA – means PIECE

IFTA – means OPEN

SAKKER – means CLOSE

NUM – means SLEEP

DIAHMOND – means ALWAYS

SHOOKOL – means WORK

ABLA – means BEFORE

BAAD – means AFTER

ILTIHAB – means INFECTION

ASSACIA – means ALLERGY

FIDAH – means USE /MEANING

YANNI – means MAYBE

TAABEN – means TIRED or SICK

ASHAN – means BECAUSE

SENENCES YOU MAY USE

MAFI FIDAH – means NO USE or MEANING

KIEF YANNI? – means WHAT (HOW IS THAT?) DO YOU MEAN?

GATRA MOS LASM, ASHAN MA INDIK ILTIHAB – means YOU DON’T HAVE TO USE AN EYE DROP, BECAUSE YOU DON’T HAVE AN EYE
INFECTION.

WORDS YOU CAN USE AND HEAR WHEN SELLING

ACHERSHEY – means THAT’S IT (LAST PRICE)

KAFIFFHA – means LIGHT

SAMEEK – means THICK

RAFIAH – means THIN

FAHAS – means CHECK

DAGIL – means HEAVY

KHATCH – means SCRATCH

KUDUZZ – means SCRATCHES

AFWAN – means EXCUSE

MA ALISH – means SORRY

AFDHAL – means BETTER

ABADAN – means NEVER

MAHAL – means SHOP

MODER – means MANAGER

ESHTAN-NI – means WAIT (FEMALE)

ESHTAN-NA – means WAIT (MALE)

HALTA – means CAN

TAZBIT – means ADJUST

WAZSA – means LOOSE

MOSHKILLA – means PROBLEM

FALTURRA – means INVOICE

MOMOJUD – means NOT HERE or DON’T HAVE

YABBI – means WANT or NEED

ZIV – means GIVE

AOUS – means YOU NEED (EGYPT)

HAGA – means SOMETHING

EJI – means COME

TA AL – means COME (present)

HELWA – means NICE or BEAUTIFUL

CASUALLET – means CASUAL

TIKANA – means MORE ELLEGANT

SMALLIK – means THE HEAD CLOTH SAUDI USE

AHKHID – means SURE

ANDA – means SHOUT

FICKRA – means IDEA

ZAID – means HAPPY

SAAH – means RIGHT

ZA ALINA – means ANGRY

ALEFEKRA? – means WHAT ABOUT?

AH LIF – means YOU KNOW

BUSTLE – means SEE (same as SHOUF)

AMELI? – means WHAT CAN I DO?/MAY I HELP YOU?

YA SALLAM – means NICE, VERY GOOD

BUKRA SUPHA – means TOMORROW MORNING

BUKRA BILLIL – means TOMORROW NIGHT

MOZ ZIBBA – means IT’S A BIG PROBLEM

HORMA – means LADY

RAGUL – means MAN

MAKTAB – means OFFICE

MOSTASFA – means HOSPITAL

COLORS – ALWAN

COLOR – LAUN

BONNI – BROWN

AZLE – HAZEL

AZRAK – BLUE

ROMADI – GRAY

AKDHAR – GREEN

TERQUAZI – AQUA

AZRAQ – BLUE

AHMAR – RED

ASWAD – BLACK

ABYAT – WHITE

NUMBERS WE MUST KNOW

0) SIFR. 1) WAHID. 2) ETHNIN. 3) THALATHA. 4) ARBA-A. 5) KHAMSAH. 6) SITTAH. 7) SABAA. 8.) THAMANIA. 9) TISAA. 10) ASHRAH. 11)
HADASH. 12) ITNASH.13) TALATASH. 14) ARBATASH. 15) KHAMSATASH. 16) SITASH. 17) SAB- ATASH. 18) TOMANTASH. 19) TIS ASH. 20)
ISHRIN. 21) WAHID O ISHRIN. 23) ITHNIN O ISHRIN. 23) TALAT O ISHRIN. 24) ARBA AT O ISHRIN25) KHAMSAT O ISHRIN. 26) SITTAT O
ISHRIN. 27) SAB AT O ISHRIN.28) TOMANIA O ISHRIN. 29) TISAT O ISHRIN. 30) TALATIN. 31) WAHID O TALATIN. 32) ITHNIN O TALATIN.
33) TALAT O TALATIN. 34) ARBA AT O TALATIN. 35) KHAMSAT O TALATIN. 36) SITTAT O TALATIN. 37) SAB AT O TALATIN. 38) TOMANIA O
TALATIN. 39) TISAT O TALATIN. 40) ARBA IN.41) WAHID O ARBAIN. 42) ITHNIN O ARBAIN. 43) TALAT O ARBAIN.44) ARBA AT O ARBAIN.
45) KHAMSAT O ARBAIN. 46) SITTAT O ARBAIN.47) SAB AT O ARBAIN. 48) TOMANIA O ARBAIN. 49) TISAT O ARBAIN. 50) KHAMSIN. 51)
WAHID O KHAMSIN. 52) ITHNIN O KHAMSIN. 53) TALAT O KHAMSIN. 54) ARBA AT O KHAMSIN. 55) KHAMSAT O KHAMSIN. 56) SITTAT O
KHAMSIN. 57) SAB AT O KHAMSIN. 58) TOMANIA O KHAMSIN. 59) TISAT O KHAMSIN. 60) SITT IN. 70) SAB IN. 80) TOMAN IN.90) TIS IN.
100) MIYYA. 101) MIYYA O WAHID. 102) MIYYA O ITHNIN.110) MIYYA O ASHARA. 111) MIYYA O HADASH. 112) MIYYA O ITHNASH.113)
MIYYA O TALATASH. 114) MIYYA O ARBATASH. 115) MIYYA O KHASATASH. 116) MIYYA O SITTASH. 117) MIYYA O SAB ATTASH.118) MIYYA
O TOMANTASH. 119) MIYYA O TISASH. 120)MIYYA O ISHRIN.130) MIYYA O TALATIN. 140) MIYYA O ARBA IN. 141) MIYYA WAHID O
ARBAIN. 150) MIYYA O KHAMS IN. 160) MIYYA O SITT IN. 170) MIYYA O SAB IN. 180) MIYYA O TOMANIN. 190) MIYYA O TIS IN. 200)
MITAIN. 300) TALAT- MIYYA. 400) ARBA-MIYYA. 500) KHAMS-MIYYA. 600) SITT-MIYYA. 700) SAB A-MIYYA. 800) TOMAN-MIYYA. 900) TIS
A-MIYYA. 1,000) ALF. 1,100) ALF O MIYYA. 2,000) ALF-AIN . 3,000) TALAT-ALAF. 4,000) ARBAT-ALAF. 5,000) KHAMSAT-ALAF. 10,000)
ASHRAT-ALAF. 100,000) MIYYAT-ALF. 1,000,000) MILYON. 2,000,000) MILYON-AIN. 3,000,000) TALAT-MALAYIN.

Share this:

* Facebook
* X
*

Like this:

Like Loading...

Related

November 25, 2006 - Posted by edoc | Blogroll, optometrist, pinoy, Saudi, Uncategorized

17 Comments »

1 Thank you very much for these arabic translations. These helped me a lot. Can you give more terms about employment, for ex: employment
contract, expire, passport, etc…

Thank you.

*
Comment by Margie Isidro⚠️ | July 28, 2016 | Reply

2 Useful indeed.

*
Comment by Maina moses | September 2, 2016 | Reply

3 Really great.Love you

*
Comment by SAM | September 25, 2016 | Reply

4 ano po meaning ng ikba? hnd qo po alm kng yn ung right spelling thanks po

*
Comment by Mary Jane Garengo | October 23, 2016 | Reply

5 What is napar?

*
Comment by abm (@abmondejar) | October 27, 2016 | Reply

* Itong kasma ko or kasama mo halimbawa ana napar ada jadid. Itong kasama ko bago.

*
Comment by Jhun⚠️ | November 25, 2016 | Reply

* Napar/nafar.. refers to ‘taO’ or someone.

*
Comment by alanis | July 13, 2017 | Reply

6 Good and helpful

*
Comment by Srigirivas R | November 29, 2017 | Reply

7 What does Mojud mean. This is my name and my mother told me that it had a meaning in arbic.

*
Comment by Mojud Juarez | March 5, 2018 | Reply

* means available / present

*
Comment by mark | December 25, 2019 | Reply

8 Good it helps me a lot to understand Arabic

*
Comment by Aslam | December 29, 2018 | Reply

9 Very good

*
Comment by Mohammed | February 28, 2019 | Reply

10 Really great.awesome job

*
Comment by Shijin PS | January 9, 2020 | Reply

11 Very useful

*
Comment by Carlo | July 4, 2020 | Reply

12 I need to get more wards

*
Comment by Allan | October 3, 2020 | Reply

* How can I find other words

*
Comment by Allan | October 3, 2020 | Reply

13 Thanks a million ,It’s been so helpful to me. 👏👏👏

*
Comment by Nyebaza Shivan | November 11, 2021 | Reply

Leave a Reply

« Previous | Next »

About

Have you ever wonder how does a Filipino working in Saudi Arabia? Well, lets find it out. I’ll try to show you some pictures and share some
Arabic words. So, be my guest.

dsc00018.JPG

* Recent

* unlock it
* nikon
* tripod2
* tripod
* the box
* tamron
* river front
* riverside
* kuching street
* ponti-indonesia
* getting dark
* kitlens

* Links

* WordPress.com
* WordPress.org
* davao home sweet home
* www.davaoworld.com

* Archives

* March 2009 (2)
* March 2008 (4)
* January 2008 (5)
* September 2007 (4)
* July 2007 (3)
* June 2007 (4)
* May 2007 (4)
* April 2007 (9)
* March 2007 (10)
* December 2006 (1)
* November 2006 (3)

* Categories

* Blogroll
* optometrist
* pinoy
* Saudi
* Uncategorized

* RSS

Entries RSS
Comments RSS

Site info

riyadh
Blog at WordPress.com.
%d bloggers like this:

*
