#+title:      my.gratitude.journal.org
#+date:       [2024-04-28 Sun 20:58]
#+filetags:   :priv:
#+identifier: 20240428T205802

* add more entries here.

* 2024-05-04
***** Thank you God for this gift of life today. Thank you for giving me the opportunity to start another day of my existence in this world. Thank you for giving me the energy to do my daily yoga morning routine before i start my day. Please i pray you keep my family in Iloilo safe from harm. Please guide my wife as she goes to join her circle of friends for their get-together. Please watch over my kids as well as they go on with their day at home.
***** I ask for your guidance as i start my day and week of work today. Please give me the knowledge to decide what is good and bad. Please give me the wisdom to decide if I will prepare packing up in anticipation of the coming re-assignment as our project comes to an end.
***** Tomorrow please guide me as I embark my return to hospital to get another checkup by the doctor re my BP monitoring.
* 2024-05-03
***** Thank you Lord for giving me a new day to start my life. I got up half past 4 am and thank you for giving me the capacity to perform my daily yoga routine plus walking running for 45 minutes outdoors. Thank you for giving me the strength to do so.
***** Thank you for protecting my family back home plus my sibs in CAnada. Thank you for guiding us today and I pray for your continuous blessings as we carry on with our day.
***** Thank you for giving me the energy to do my night time yoga. I'm feeling much better nowadays.
***** Tomorrow i pray you guide me in checking my blood pressure using my newly purchased Omron M6 monitor.
* 2024-05-02
***** Thank you for guiding me to finish this day.
***** Thank you for making nene Sonia arrived safely in Canada and now together with her family.
***** I have canker sores and suffering from pain but thank you for giving me the capacity to resolve it by getting home remedy items to make me better in the coming days.
* Today April 28/24 I start my gratitude diary in this machine.
*** I have back pain but thank you Lord for giving me the capacity to do yoga exercise and improve my back.
*** I plan to continue this in the foreseable future and also incorporate walking/running in my exercise routine.
*** Thank you for the success of nene Sonia's dinner hosting today back home. I ask your mercy and blessing that you guide here in her coming return trip to Canada this Wednesday May 1.
*** Thank you for making a success my money transfer to my wife's account for their monthly home allowance.
*** Tonight as I get myself ready to sleep i ask for your guidance to protect me from bad spirits roaming at night seeking harm to restless souls, amen.
