#+title:      my.gratitude.journal.org
#+date:       [2024-04-28 Sun 20:58]
#+filetags:   :priv:
#+identifier: 20240428T205802

* add more entries here.

* 2024-05-02
***** Thank you for guiding me to finish this day.
***** Thank you for making nene Sonia arrived safely in Canada and now together with her family.
***** I have canker sores and suffering from pain but thank you for giving me the capacity to resolve it by getting home remedy items to make me better in the coming days.
* Today April 28/24 I start my gratitude diary in this machine.
*** I have back pain but thank you Lord for giving me the capacity to do yoga exercise and improve my back.
*** I plan to continue this in the foreseable future and also incorporate walking/running in my exercise routine.
*** Thank you for the success of nene Sonia's dinner hosting today back home. I ask your mercy and blessing that you guide here in her coming return trip to Canada this Wednesday May 1.
*** Thank you for making a success my money transfer to my wife's account for their monthly home allowance.
*** Tonight as I get myself ready to sleep i ask for your guidance to protect me from bad spirits roaming at night seeking harm to restless souls, amen.
