* 2023
** 2023-09 September
*** 2023-09-12 Tuesday
**** Nix Search options this is valuable to set up the various million options available to the user.
Added on [2023-09-12 Tue 06:53]

 [[https://search.nixos.org/options][NixOS Search]]
*** 2023-09-13 Wednesday
**** See below the notes I achieved for todays time stamp.
Entry date [2023-09-13 Wed 21:42]

* Notes of stuffs learned today

So what shall I do now?
Well I just finished viewing 2 videos of Prot and they are stored in the viewed folder under Videos dir.
I want to document or make a record of those viewed videos in a journal in Emacs.
- Emacs：_introduction_to_VC_(version_control_framework)_[SQ3Beqn2CEc].mp4
- Emacs：_Learn_to_ask_for_Help_and_write_Elisp_[46w9e4GAjsU].mp4
- Emacs：_mark_and_register_basics_[TJrAkCyH6Dk].mp4
- Emacs_Org_mode_basics.mp4
- Philosophy_life_lessons_from_the_hut.mp4
* DONE Also I want to save the shownotes of the last viewed video so I can gain information of the topics that were discussed.
CLOSED: [2023-09-14 Thu 05:50]
:LOGBOOK:
- State "DONE"       from "CANCELLED"  [2023-09-14 Thu 05:51]
- State "CANCELLED"  from "WAITING"    [2023-09-14 Thu 05:50]
- State "WAITING"    from "CANCELLED"  [2023-09-14 Thu 05:50]
- State "CANCELLED"  from "WAITING"    [2023-09-14 Thu 05:49]
- State "WAITING"    from "CANCELLED"  [2023-09-14 Thu 05:49]
- State "CANCELLED"  from "WAITING"    [2023-09-14 Thu 05:48]
- State "WAITING"    from "CANCELLED"  [2023-09-14 Thu 05:48]
- State "CANCELLED"  from              [2023-09-14 Thu 05:48]
:END:

* DONE dired mode defaults to long list view not the short one so I need to do a setq variable declaration to achieve this. TIP: go to the dired buffer then do C-h m then find the function that toggles the long/short view mode then setq that function in your init file, somthing to that effect.
CLOSED: [2023-09-14 Thu 05:53]
:LOGBOOK:
- State "DONE"       from "NEXT"       [2023-09-14 Thu 05:53]
:END:

* TODO note to self NTS: im struggling changing the state of a todo item to done. press shift+right arrow continuously until you get the done state.
:LOGBOOK:
- State "NEXT"       from "DONE"       [2023-09-14 Thu 05:54]
- State "DONE"       from "NEXT"       [2023-09-14 Thu 05:54]
:END:

* TODO Consider checking/trying out emacs-w3m port
https://github.com/emacs-w3m/emacs-w3m

* See this link for Prots shownotes to his video below
https://protesilaos.com/codelog/2022-01-31-learning-emacs/
https://protesilaos.com/emacs/dotemacs
1) Emacs：_Learn_to_ask_for_Help_and_write_Elisp_[46w9e4GAjsU].mp4
