* Begin writing waray waray words for practice learning the dialect

* Nagsabat an anghel, "Ako si Gabriel na suruguon sa atubangan san Diyos kag sinugo niya ako agod ipaabot sa imo ini na mga maayo na barita. Tandai ini. Magigin apa ka kag dili ka makasurmaton hasta na dili ini mangyari tungod na dili ka nagatuod san mga ginapangsabi ko sa imo na matuod man gayod na mangyayari sa tama na panahon."

* Myintras an mga two sa luwas na nagahulat kan Zacarias nagngaralas kun nano kay nadugay siya sa sulod. San pagluwas niya wara na siya makasurmaton sa inda kag nagapasabot na lang sa inda paagi san kamot kay apa na siya. Kaya napanginanuhan ninda na si Zacharias nakakita sin pangitaon didto. San matapos na an panahon san iya pagtrabaho bilang padi nag uli na siya.

* Wara madugay an iya asawa na si Elisabet nagbudos kag sa sulod san lima ka bulan nagkulong siya sa inda balay. Ginsabi niya, "Himo ini san Ginoo sa akon kay sa iya kagustuhan hinali an kaaluhan na akon gintios sa mga tawo."
* San ikaunom ka bulan san pagbudos ni Elisabet sinugo san Dios an anghel na si Gabriel pakadto sa Nazaret na usad na lungsod sa Galilea. Nagpakadto siya kan Maria na usad na birhen na ginapangasawa ni Jose hali sa lahi san dati na hadi na si David. Pag-abot san anghel sa balay sani nagsabi sya, "Maglipay ka, ikaw an pinalabi san Dios kag ada sa imo an Ginoo."
* Kinulbaan gayod si Maria san ginapanurmaton sa iya kag gin isip-isip kon nano an gusto sabihon sani. Pero ginsabihan siya san anghel, "Ayaw kahadlok Maria, kay pinalabi ka sa mata san Dios. Tandai, magabudos kag magaanak ka'n lalaki kag pagangaranan mo siya'n Jesus. Palabawon siya kag pagatawagon na Anak san Pinakalabaw na Dios. Pareho san iya kalulululuhan na si David pagapahadion siya san Ginoo'n Dios. Didto magahadi siya san lahi ni Jacob hasta na lang kag an iya kahadian wara'n katapusan."
* Niyan, ginhunga ni Maria an anghel, "Pero pan-o ini mangyari na adi wara ako'n asawa?"
* Ginsabat siya san anghel, "Mapakada sa imo an Espirito Santo kag pagapabuduson ka san gahom san Pinakalabaw na Dios. Kaya an imo iaanak magin banal kag pagatawagon na Anak san Dios. Kitaa, bisan ngani an imo primahon na si Elisabet apisar san iya kagurangon nagbudos. Siya na ginatawag san mga tawo na baog yana ikaunom na ka bulan an iya pagbudos, kay wara'n imposible sa Dios.
"
* Kaya nagsabat si Maria, "Suruguon ako san Ginoo. Mangyari lugod ini sa akon na ginsabi mo." Tapos ginbayaan na siya san Anghel.

* An Pagbisita ni Maria kan Elisabet
** Pagkalipas sin pira ka adlaw nag apura si Maria pakadto sa usad na lungsod sa kabukidan san Judea, kag pagsulod sa balay ni Zacarias ginkamusta si Elisabet.
** Pakabati lang ni Elisabet san pangumusta ni Maria ada na sa iya an gahom san Espirito Santo kag insigida an bata sa iya tiyan naghiwag. Tapos nagsurmaton si Elisabet sin makusog, "Pinalabi ka sa tanan na mga babayi kag pinalabi man an bata na ada sa imo tiyan. Malipay gayod ako na ginabisita san iloy san akon Ginoo kay pakabati ko lang sa imo pangumusta an sa akon tiyan naghiwag sa dako na kalipay. Oo, malipay ka na nagtuod na matutuman an gintuga sa imo san Ginoo."
