*
Here's a list of Tagalog words and their Waray equivalent. I compiled this with the help of my fellow Waray friends. If
there are erroneous entries on this list or if you want to add some more words, please let me know so I can update this.
Salamat! (ES means Eastern Samar; NS, Northern Samar.)

             Update: Here's a new post. It's a list of sentences in Tagalog translated to Waray. The link is right here:

             ==============

             Tagalog to Waray and Waray to Tagalog Sentences

             =============

             *
             halaman - tanaman
             *
             A
             Aalis - malakat; magikan (NS)
             Abaniko - paypay; payahan
             Abugado - abugado
             Abo - abo; agbon
             Agahan/almusal - pamahaw
             Ahas - halas
             Akbay - sangbay; sangkay
             Akin - akon
             Ako - ako
             Akusa - akusar
             Alagaan - atamanon
             Alak - irimnon
             Alam (as in "Alam ko.") - maaram
             Alikabok - taputapo
             Alila - uripon
             Alis - lakat; gikan (NS)
             Alisin - tanggalon
             Alon - balud
             Alupihan - ulalahipan; lalahipan
             Ama - amay
             Amin - amon
             Amo - agaron
             Anay - anay
             Anim - unom
             Anino - lambung; dagaw
             Ang - an
             Angkan - tulin; rawog (ES)
             Ano - ano; nano (NS)
             Apat - upat
             Apoy - kalayo
             Araw (day in English) - adlaw
             Araw (sun in English) - adlaw; sudang (NS)
             Asim - aslom; asom (NS)
             Aso - ayam
             Asukal - asukar
             At - ug; ngan
             Atay - atay
             Ate - ate; mana
             Atin - aton
             Atsay - binata (NS)

             B
             Baba - sulang
             Babae - babaye
             Babasagin (hal., babasaging plato) - maburuong
             Babasagin - (hal., babasagin ang alkansya) - bubuungon
             Bading/bakla - bayot
             Bahay - balay
             Bagang - bag-ang
             Bagay (hal., mga bagay) - butang
             Bagay (hal., Bagay tayo.) - angay
             Bago - bag-o
             Bagoong - ginamos; budo
             Baitang - hagdan
             Baka (hal., Baka dumating siya bukas.) - bangin; tingali
             Bakal - puthaw
             Bakit - kay ano; kay nano (NS)
             Balae - balaye
             Balahibo - barahibo; burahibo
             Balat - panit
             Balbas - barbas; burungos (NS)
             Balbon - barbon
             Balikat - sugbong
             Baliktad - balikad
             Balimbing - malimbin
             Balisong - dipang
             Baliw - lurong; imos (NS)
             Baluktot - kulubikob; nabalok
             Banlag - manukon
             Banlaw - bulyas
             Bangka - baluto
             Baon - balon
             Barya - sinsilyo
             Basa (to read) - basa
             Basa (hal., basa ang sahig) - mahulos
             Basag - buong
             Basket - basket; bayuong
             Bata - bata
             Batas - balaud
             Bawang - ahos; lasona (NS)
             Bayabas - mayabas
             Bayad - bayad
             Bayag - bunay
             Baywang - hawak; kupsan
             Bibig - baba; hiwa (NS)
             Bigas - bugas
             Bigat - bug-at
             Bigay - hatag
             Bihasa - hiara; higara (NS)
             Biik - pasi
             Bilang (hal., bilang iyong kaibigan) - komo
             Bilang (hal., bilang ng mga bata) - ihap
             Bilangin - ihapon
             Bilin/habilin - tugon
             Bilog - lidong; lipuyok (NS)
             Biloy - pangandiis
             Bimpo - labakara
             Binat - bughat
             Binata - ulitawo
             Bintana - bintana
             Binugbog - ginkastigo; kinastigo
             Binyag - bunyag
             Bingi - bungol
             Bingot - bungi
             Biro - intrimis; mulay (NS); suri ( NS)
             Bitak - butak
             Bituin - bituon
             Biyenan - ugangan
             Bobo - bulok
             Boses - tingog
             Bote - botelya
             Braso - butkon
             Bubong - atup/atop; bubong (NS)
             Bugbog-sarado - kastigado
             Buhangin - baras
             Buhay (alive in English) - buhi
             Buhay (life in English) - kinabuhi
             Buhok - buhok
             Bukas (hal., bukas ng umaga) - buwas
             Bukas (hal., bukas ang pinto) - abre; abrido
             Bukid - uma; iraya
             Buko - silot
             Bulag - buta
             Bulaklak - bukad
             Bulati  (earthworm in English) - wati
             Bulati - uging
             Bulok - dunot
             Bulong - huring
             Bundok - bukid
             Bunso - pudo; puto; gimamanghuri
             Buntis - burod
             Bunga - bunga
             Buntot - ikog; ukig (NS)
             Buo - bug-os
             Butas - buho; luho
             Butiki - pinit (NS)
             Butil - tipasi
             Buto (ng tao/hayop) - tul-an
             Buto (seed in English) - liso; uyas (NS)
             Buwan - bulan
             Buwaya - buaya

             C
             Char - char
             Charing - charing
             Charot - charot
             Chaka - chaka
             Chika - chika
             Chikadora - chikadora

             D
             Daan - agianan; dalan; kalsada; sigad (NS)D
             Daga - yatot
             Dahil - kay; tungod
             Daigdig - kalibutan
             Dalaga - daraga
             Dalampasigan - baybayon
             Dalawa - duha
             Daliri - tudlo; kuramoy
             Damit - bado
             Dapo - hapon
             Demonyo - manunulay; panulay; demonyo; yawa
             Dibdib - dughan
             Dighay - dug-ab
             Diko - ingko
             Dila - dila
             Dilaw - dulaw
             Dito - dinhi; didi
             Ditse - inse
             Dingding - bungbong; lipon (NS)
             Diyan - dida; doon (NS)
             Diyos - Diyos; Dios; Dyos
             Doon - didto
             Duktor - duktor
             Dura - tupra; luda
             Duwag - matalaw; hadlukon; hadok (NS)

             E
             Eroplano - edru/idru
             Ewan - Ambot

             G
             Gabi - gab-i
             Gabi (root crop) - gaway
             Galaw - gios; kiwa (NS)
             Galing (hal., galing sa bahay) - tikang
             Galit - kasina
             Galos - samad
             Gamot - tambal; bulong (NS)
             Ganda - husay; baysay
             Ganti - bulos
             Gata ng niyog - hatok; lunop (NS)
             Gawa - himo; hinimo; binuhat
             Gilagid - lagos
             Ginto - bulawan
             Gitna/sentro - butnga
             Gubat - kagurangan; kagugub-an
             Gulay - utanon; utan
             Gulong - lidong
             Gumulong - naglido (NS)
             Gupit - arot; burog (NS)
             Guro - magturutdo; paragtutdo (NS)
             Gusali - bilding
             Gusot - kurumos
             Gusto - karuyag

             H
             Hakbang - piktaw
             Halaman - tanaman
             Haligi - harigi; sibol (NS)
             Halik - harok
             Halimbawa - pananglitan
             Haluin - ukayon
             Hamog - tun-og
             Handa - andam; preparado
             Hapag-kainan - karaunan; lamesa
             Hapon - kulop
             Hapunan - panihapon; pangiklop
             Hari - hadi
             Hati - tunga
             Hatinggabi - katutnga
             Hawak - kapot
             Higa - higda
             Higaan - higdaan
             Hikab - huyam
             Hikaw - ariyos
             Hila - butong; danas
             Hilamos - hiram-os; huram-os
             Hilo - lipong
             Hindi - diri
             Hininga - ginhawa
             Hinirang - pinili
             Hinlalaki - tumaragko
             Hinliliit - kumayingking
             Hintuturo - tumurutdo
             Hintay - hulat
             Hita - paa
             Hiwalay - bulag
             Hubad - hubo
             Huli - urihi; pukis
             Huwag - ayaw

             I
             Iba - iba; lain
             Ibaba - ubos; ilarom
             Ibabaw - igbaw; bawbaw
             Iba-iba - magkadirudilain; magkadurudilain
             Ibon - tamsi
             Ihaw - sugba
             Ikaw - ikaw
             Ikot - libot; talibong
             Ilalim - ilarom
             Ilaw - suga; layt
             Ilog - salog
             Ilong - irong
             Ina - iroy
             Inaanak - kinugos
             Inaantok - pinipiraw; nahingangaturog; hingaturugon
             Inahin - umagak
             Inahing baboy - pakal
             Inakusahan - ginbutangbutangan
             Inihaw - sinugba
             Inom - inom
             Inom ng gamot - tumar
             Inyo - iyo
             Inggit - indig
             Ipa - upa
             Ipaalam - ipasabot; pasabuta
             Ipakisuyo - ipaalayon
             Ipis - bangka
             Isa - usa; sayo
             Isahog - isakot; ilun-od
             Isip - hunahuna
             Itak - sundang; bulo; purang
             Itik - pato
             Itim - itom; pili (NS)
             Itinulak - ginduso; iginduso; gintulang
             Itlog - bunay
             Iwas - likay; iskip
             Iyak - tuok; uraw (ES); tangis (NS)
             Iyo - imo

             K
             Kaba - kulba
             Kababaihan - kababayin-an
             Kabit/kulasisi - kabit; pinya (NS)
             Kahapon - kakulop; kahapon
             Kaibigan - sangkay
             Kailangan - kinahanglan
             Kalabasa - karubasa; karabasa
             Kalabaw - karabaw
             Kalahati - katunga
             Kalalakihan - kalalakin-an
             Kalapati - sarapati
             Kalawang - baga
             Kalingkingan - kumayingking
             Kaliskis - hingbis
             Kama/papag - kama; katre
             Kamag-anak - kaurupdan
             Kamay - kamot
             Kambal - karuha
             Kambing - kanding
             Kami - kami
             Kamoteng-kahoy - bilanghoy; lagikway (NS)
             Kampana - lingganay; bagtingan
             Kampi - ugop
             Kanila - ira; kanira/kanra (NS)
             Kanin - kan-on; luto (NS)
             Kantot - iyot; tatsi (NS)
             Kapal - dakmol
             Kapatid - bugto
             Kapit-bahay - amyaw; hipid (NS)
             Kasal - kasal
             Kasalanan - sala
             Kasali - kaapi; api
             Kasalo - kahampang
             Kasama - kaupod; upod
             Kasambahay - kabulig
             Kasinungalingan - buwa
             Katapat/kaharap - kaatubang
             Katawan - lawas
             Katawatawa - pataraw-an; makatatawa (NS)
             Kati - katol
             Katulong - kabulig
             Kaugalian - pamatasan; mga nahiaraan; mga nahigaraan (NS)
             Kawali - karaha
             Kawawa - kairo
             Kay - kan
             Kayo - kamo
             Kilala - kilala/nakilala; nakila/kila (NS)
             Kilikili - irok
             Kiliti - girok; guyok
             Kindat - kiro
             Kinakabahan - ginkukulba; ginkukulbaan; kinukulbaan
             Kinakapatid - igso
             Kinang - inggat
             Kintab - inggat
             Kinumpronta - ginsukmat; sinukmat (NS)
             Kirot - ngutngot
             Kisame - alkuba
             Kita (sa trabaho) - kita
             Kita (we in English) - kita
             Kuba - buktot
             Kuko - kulo
             Kulambo - moskitero
             Kulang - kulang
             Kulangot - dungot
             Kulo - kaladkad
             Kulot - kurong
             Kulubot - kuros; nakuros
             Kumot - taklap; taplak (NS)
             Kumpara - tanding
             Kumukulo - nakaladkad
             Kurot - kubot
             Kuto - kuto
             Kuya - kuya; mano; manoy

             L
             Laba - laba; bunak
             Lababo - lababo; banggirahan
             Labahan - bunakan
             Labas - gawas
             Labas- masok - sulod-gawas; sulod-guwa
             Labi - im-im
             Lagari - sarutso
             Laglag (abortion) - purak
             Lagnat/sinat - hiranat
             Lahat - ngatanan
             Lakwatsa - lakwatsa; kalalag (NS)
             Lalaki - lalaki
             Lamok - namok
             Langgam - tubak; tigasaw (NS)
             Laro - mulay; uyag
             Laruan - mulayan; uyagan (NS)
             Laylayan - sagyad
             Leeg - liog
             Libag - buring; during (NS)
             Libing - lubong
             Ligo - karigo; parigo
             Lihim - sikreto
             Likod - likod; gutok (NS)
             Likod ng bahay - luyo hit' balay; luyo san balay (NS)
             Lima - lima
             Lindol - linog
             Luha - luha
             Lukso/lundag - lukso
             Lunok - tulon
             Lupa - tuna
             Luya - luy-a

             M
             Maalat - maasin
             Maalinsangan - magirhang; maalindanga
             Maaliwalas - mahiwarang
             Maalon - mabalud
             Maanghang - maharang
             Maarte - maartehon
             Maasim - maaslom; maasom (NS)
             Maawain - maluluy-on; luluuyon
             Mababaw - hababaw
             Mabagal - mahinay
             Mabaho - mabaho; mabang-og (NS)
             Mabait - buotan
             Mabango - mahamot; mahumot (NS)
             Mabigat - mabug-at
             Mabilis - malaksi
             Madaling araw - maagahon; kaagahon
             Madilim - masirom
             Madulas - madalunot
             Maga - hubag
             Magaan - magaan
             Magaling - makarit; listo (NS)
             Maganda - mahusay; mabaysay (NS)
             Magbilang - mag-ihap
             Magbihis - magliwan
             Magkapatid - magbugto
             Magluto - magluto
             Magpaalam - magsarit
             Magpaganda - magpahusay; magpabaysay
             Magpagupit - magpaarot; magpaburog
             Magpapayat - magpagasa; magpahugos (NS)
             Magparamdam - magpaabat
             Magparaya - magpaumaya; magpabalunod (NS)
             Magsasaka - mag-uuma; parag-uma (NS)
             Magsaing - magtuon; magtug-on (NS)
             Magulo - masamok
             Mahaba - halaba
             Mahal (hal., mahal ang mga bilihin) - mahal
             Mahal (hal., ikaw ang aking mahal) - hinigugma
             Mahal (hal., mahal kita) - ginhihigugma
             Mahina - maluya
             Mahirap - makuri
             Mahirap (hal., mahirap ang pamumuhay) - pobre; kablas
             Mahiya - maawod; maalo
             Mahiyain - awdanon; aawuron; aaluhon; sisiuron
             Maikli - halipot
             Maiksi - halipot
             Mainit - mapaso
             Mainit na tubig - laso
             Maingay - maaringasa; maliya (NS)
             Maitim - maitom; mapili (NS)
             Makapal - madakmol
             Makamandag - malara
             Makati - makatol
             Makikisuyo - makikialayon
             Makinis - mahamis
             Makirot - mangutngot
             Makunat - mahunat
             Malakas - makusog
             Malaki - dako; darako (NS)
             Malalim - halarom; hilarom
             Malamig - mahagkot; mapinit (NS)
             Malandi - pikat; uragan (NS)
             Malapad - hilapad; halapad
             Malapit - harani; hirani
             Malaswa - malaw-ay
             Malayo - harayo; hirayo
             Malibog - uuragon
             Maligamgam - malanhod
             Maliit - gutiay; ditoy (NS)
             Malinamnam - marasa
             Malinaw (hal. malinaw na tubig/clear water) - malihaw (NS)
             Malinaw (hal. Malinaw ang kanyang mensahe) - klaro
             Malinis - malimpyo
             Maliwanag - malamrag; masuna (NS)
             Malunggay - kamalunggay
             Malutong - makarubkarob; maragumo (NS)
             Mamaya - unina; niyan
             Manipis - manipis
             Mantika - mantika; asyete (NS)
             Manugang - umagad
             Mangingisda - parapangisda; paraghulaw (NS)
             Mapagmataas - mapinahitas-on
             Mapagpakumbaba - mapinaubsanon
             Mapait - mapait
             Mapanghi - mapar-ot; mapanghak
             Maputi - mabusag
             Marami - damo; daramo (NS)
             Maramot - hakog; halot; duhong
             Mare - madi
             Martilyo - martilyo
             Marumi - mahugaw; marigna (NS); marigsok (NS)
             Marunong - listo (NS)
             Marupok - maruya
             Mas - mas; labaw
             Masarap - marasa
             Masakit - maul-ol; masakit; masuol (NS)
             Masaya - malipayon
             Masikip (hal., masikip na damit) - huot; masuot
             Masikip (hal., masikip na lugar) - piguot
             Masipag - maduruto
             Mata - mata
             Mataba - matambok; mataba (NS)
             Matabang - matapsi
             Matagal - maiha
             Matalino - baltok
             Matamis - matam-is
             Matanda - lagas; arug/ arog (NS)
             Matandang dalaga/binata - angot
             Matapang - maisog
             Matibay - madig-on; marig-on; masarig
             Mayabang - hambog
             Mayaman - riko; salapian; kwartahan
             Mayroon/Meron - may-ada; yaon/mayaon (NS)
             Medyo hambog - hambugon (NS)
             Minamahal - hinigugma; higugmaon
             Mukha - nawong; kahimo (NS)
             Mumog - limugmog
             Mura (hal., mura ang mga bilihin) - barato
             Mura (hal, pagmumura) - buyayaw

             N
             Nababagot - nauuyam
             Nabitiwan - nabuhian
             Nadapa - nahipakulob
             Nadulas - nahipalindas
             Nag-aalab - naglalarab
             Nagkakagusto - naruruyag
             Nagkagusto - naruyag
             Nagkasalubong - nagkatapo
             Naglalagablab - naglalarab
             Nagmamadali - nag-aapura
             Nagpalaglag - nagpapunit; nagpapurak (NS)
             Nagtaka - napausa; nahingaratan (NS)
             Nagulat - kinalasan; nahingaratan (NS)
             Nahilo - nalipong
             Nahihiya - naaawod; naaalo; nasisiod
             Nahiya - naawod; naalo; nasiod
             Na-inlab - nahigugma
             Nakababatang kapatid - manghod
             Nakakabagot - mauyam
             Nakakainis - makaharangit; makalalangot (NS)
             Nakalimot - nahingalimot; nalipat
             Nakasimangot - namusdot; namusurot
             Nakatatandang kapatid - magurang
             Nananalaytay - naabid
             Nanay - nanay
             Nanliligaw - namamadayaw (NS)
             Napilitan - napiritan
             Napulot - napurot; napurutan
             Nararamdaman - binabati; inaabat
             Narito - aanhi; aadi; adi (NS)
             Nars (nurse) - nars
             Natulala - hinutuwong (NS)
             Nilikha - binuhat
             Ninyo - niyo
             Ningning - inggat
             Niyog - lubi
             Noo - agtang
             Nunal - Arom

             Ng
             Ngala-ngala - ngala-ngala
             Nganga - nganga
             Ngayon - yana
             Ngipin - ngipon; tango
             Ngiti - hiyom
             Ngiwi - hiwit
             Nguso - nguyo-nguyo
             Nguya - kisam

             O
             O (or in English) - o
             Oo - oo
             Orasan - relo

             P
             Paa - tiil; siki (NS)
             Paalala - pahinumdom
             Paborito (hal., paboritong pagkain o bagay) - paborito
             Paborito/mahal (hal., paboritong anak o kapatid) - pinaura; palangga
             Pagbutihan - upayon
             Pag-ibig - gugma; gubma
             Pagpapatawad - pagpasaylo
             Pagtulak - pagduso
             Pahinga - pahuway
             Pakpak - pako
             Pako - raysang
             Palaaway - makiaawayon
             Palabiro - maintrimis; mamulay (NS); masuri (NS)
             Palaka - pakra; katsapa (NS)
             Palakaibigan - makisasangkayon
             Palapag - andana; eskalon
             Palaso - pana
             Palatandaan - tigaman
             Palay - humay; paray
             Palikuran/kubeta - kasilyas; toylit; CR
             Pamangkin - umangkon
             Panaginip - inop
             Panalangin - pag-ampo; pangamuyo
             Panata - panaad
             Pantalon - sarwal
             Pangako - saad
             Panganay - suhag; gigugurangi
             Panginoon - Ginoo
             Pangit - maraksut; maraut; mabara (NS)
             Panggatong - sungo
             Papansin - parayawan; padayaw
             Papaya - kapayas
             Para/upang - basi
             Para (for in English) - para
             Paratang - butangbutang
             Pare - padi
             Pares - padis
             Pari - padi
             Paruparo - alibangbang
             Pasasa/pakasarap - pakarasa
             Pasaway - pasarawayon; pasusuhayon
             Pasok - sulod
             Patawarin - pasayluon
             Patong - tungbaw
             Patuloy - padayon
             Pawis - hulas
             Payat - magasa; mahugos (NS)
             Payo - sagdon
             Payong - payong
             Peklat - ulat
             Pera - kwarta
             Pikit - piyong
             Pilak - silber
             Pilik-mata - pirok
             Pilipit - birikis
             Pilit - pirit
             Pinaasa - ginpalaum
             Pinagalitan - gin-isgan
             Pinagpawisan - ginbalhasan; pinanhulasan
             Pinggan - pinggan
             Pinsan - patud/patod
             Pintasera/pintasero - matamay
             Pinto/pintuan - purtahan
             Pinuri - gindayeg
             Pintura - pintar
             Pipi - ngula
             Pisngi - bayhon
             Pitaka - pitaka
             Pito - pito
             Plano - larang
             Pugita - kugita
             Puki - puday; puyet
             Pula - pula; baga (NS)
             Pulutan - sumsuman
             Pumayat - gumasa; naghugos
             Punas - trapo
             Pusa - misay; miyay; uding; ipo (NS)
             Pusit - nuos; kanuos
             Puso - kasingkasing
             Pusod - pusod
             Puson - pus-on
             Putol ang kamay - pungkol
             Punda - punda
             Puti - busag
             Putik - lagay
             Puwet - bubot
             Puyat - piraw
             Pwera usog - pwera buyag

             R
             Relo - relo
             Repolyo - repolyo
             Resbak - bulos
             Reserba - reserba
             Reseta - reseta
             Resibo - resibo
             Resulta - resulta
             Reyna - rayna

             S
             Sagana - bastante
             Sagot - baton
             Sahig - salug/salog
             Sahog - sakot
             Sakal - kibol
             Sakong - bul-ong
             Salamin - salamin; espiho
             Salisi - baluknis
             Salita - pulong
             Sampal - taplong; tapal
             Sampay (hal., Isampay mo ang damit.) - palaypay
             Sampu - napulo
             Sana - unta; kunta
             Sana all - unta/kunta ngatanan
             Sanay - hiara; higara (NS)
             Sandok - luwag; sakwitan
             Sanga ng niyog - palwa; paklang
             Sangkalan/tadtaran - tadtaran
             Sapat - tama; eksakto
             Sapatos - sapatos
             Sarili (hal., sariling bahay) - lugaring
             Sarili (hal., Mahalin mo ang iyong sarili.) - kalugaringon
             Sariwa (hal., sariwang isda) - lab-as
             Sariwa (hal., sariwang hangin) - presko
             Sawsawan - sawsawan; duduan (NS)
             Saya/palda - saya
             Saya/galak/tuwa - lipay
             Si - hi; si
             Sikmura - suroksurok
             Sila - hira; sira (NS)
             Sili - harang; katsumba; sili
             Silip - hiling; sil-ing (NS)
             Simple - simple; yano
             Simba - singba
             Sinasamba - ginsisingba
             Sindi - dagkot
             Sindihan - dagkutan
             Sinigawan - ginguliatan (read this as: gin-guliatan); gingagasuran (NS; read as: gin-gagasuran)
             Sino - hino; hin-o; sin-o
             Sinturon - paha; takgong (NS)
             Sinulatan - ginsuratan
             Sinumbatan - ginbuyboy (NS)
             Sinungaling - buwaon
             Sipa/tadyak - sikad; bukbok (NS)
             Siping - ubay; durog; dirig
             Sira - guba; wakay
             Sisiw - siwo
             Siya - hiya; siya
             Siyam - siyam
             Subukan - sarihan
             Sugat - samad
             Suha - suwa (NS)
             Sulat - surat
             Sumbat - buyboy (NS)
             Sumbong - sumat
             Sumbrero - kalo
             Sumpungin/bugnutin - burugsuanon
             Supling - anak
             Supot (hindi tuli) - pisot; piyos (NS)
             Suso - suso

             T
             Tagas - awas
             Tahol - usig
             Tahimik - mamingaw
             Tainga - talinga
             Takbo - dalagan
             Talampakan - rapadapa
             Tali - higot
             Talo - pirdi
             Talon - lukso; tahaw
             Talunan - pirdido
             Tamad - hubya
             Tamod - letse
             Tandang - lalaki nga manok
             Tanim - tanom
             Tanong - pakiana; pangutana
             Tanggap - karawat
             Tanggapin - karawaton
             Tao - tawo
             Taob - kulob
             Taon - tuig
             Tapat - tangkod
             Tapat (tapat ng bahay) - yungod
             Tasa - tasa
             Tatlo - tulo
             Tawid - tabok
             Taya/pusta - taya; pusta; taun (NS)
             Tayo - tindog; tukdaw; tugbos
             Tayo (ikaw at ako) - kita
             Tibo/tomboy - lakin-on; tomboy
             Tigang - mamara
             Tigyawat - punggod
             Tihaya - huyang
             Tinanggap - ginkarawat
             Tinatwa/itinatwa - iginsalikway; ginsalikway
             Tinga - kiki
             Tinggil - tinggil
             Tingin - tan-aw; sunong (NS)
             Titi - buto; sili; putoy
             Tili - guliat; gagasud/gasud (NS)
             Tingkayad - ikid
             Tiyahin - dada
             Tiyuhin - bata
             Tono - tono; punto
             Trabaho - trabaho
             Tsimay/atsay - binata (NS)
             Tsinelas - tsinelas; sipit (NS)
             Tubig - tubig
             Tugon - sagot
             Tugtog - tukar
             Tulog - katurog
             Tulong - bulig
             Tuloy - dayon
             Tumutol - diniri
             Tumutulo - naturo; nanunuro; nanunurawig
             Tuta - ido
             Tutuli - kulali
             Tuwalya - tualya
             Tuyo (hal., tuyo ang buhok) - mamara
             Tuyo (hal., Tuyo ang paborito kong ulam.) - bulad; tamban

             U
             Ugali - batasan
             Ugat - gamot
             Ulam - sud-an; sura; igsura
             Ulan - uran
             Ulap - arum; arom
             Ulila - ilo
             Ulit - utro
             Umaga - aga
             Umiiyak - nagtutuok; nagtatangis
             Umpisa - tinikangan
             Unan - ulunan
             Unggoy - ulot
             Uod - ulod
             Upa - plite
             Upo - lingkod
             Upuan - lingkuranan; lingkuran (NS)
             Utang - utang
             Utong - yupyupan
             Utot - utot

             W
             Wala - wara; waray
             Wala sa tono - nagusaw
             Walis - siphid; silhig
             Walo - walo
             Watak-watak - burublag

             Y
             Yabag - piktaw
             Yakag - agda; uya (NS)
             Yakap - hangkop; kupkop
             Yapos - hangkop; kupkop
             Yuko - tamod; hutok
             Yumuko - tinamod; hinutok

             How to cite this blog post:

             Rhodora (2020, January 11). List of Waray Words: Tagalog to Waray. Retrieved from
             https://www.warayblogger.com/2020/01/list-of-waray-words-tagalog-to-waray.html

             ---------
             To those of you who have requested for a Waray translation of  your Tagalog sentences, please check this post:

             Tagalog Sentences with Waray Translations

             Posted by Rhodora
             *
             Email ThisBlogThis!Share to TwitterShare to FacebookShare to Pinterest
             Labels: Waray Words

             301 comments:

             1
             *
             AnonymousFebruary 27, 2020 at 7:14 AM

             Patranslate po sa Waray. Bakit mo ako pinaasa? Sana hindi mo na lang ako chinat.

             ReplyDelete
             Replies

             1
             *
             RhodoraFebruary 28, 2020 at 4:52 AM

             Kay ano nga imo ako ginpalaum? Unta waray mo na la ako ig-chat.

             Kay nano nga imo ak' ginpalaum? Kunta waray mo na la ak' ig-chat.

             Delete
             Replies

             Reply

             2
             *
             AnonymousJuly 2, 2020 at 11:14 AM

             Taga norte ka po ba? Nahalata ko la ha nga words na gingamit mo. Hehe. Taga Western po kasi ako. Parehas man la
             halos hehe salamat hni nga blog. Nangalimot na ako han iba nga words. An iba dnhe higlarom na. Ha amon an tubig,
             tubig ghapon tawag pero an hilarum na waray is "lambunaw".

             Delete
             Replies

             Reply

             3
             *
             Josephine MantoSeptember 11, 2020 at 11:21 PM

             Ano po yung waray ng I am taking an abm strand?

             Delete
             Replies

             Reply

             4
             *
             UnknownFebruary 6, 2021 at 8:57 PM

             Pa translate po ng maykatotohanan ba yang sinasabi nyo

             Delete
             Replies

             Reply

             5
             *
             AnonymousFebruary 11, 2021 at 6:05 PM

             May kamatuoran ba iton nga imo sinisiring?

             Delete
             Replies

             Reply

             6
             *
             AnonymousFebruary 15, 2021 at 9:03 AM

             Please translate "Happy Birthday to the most beautiful mom in the world"

             Delete
             Replies

             Reply

             7
             *
             AnonymousMarch 8, 2021 at 3:22 AM

             Happy birthday ha pinakamahusay nga nanay ha bug-os nga kalibutan.

             or

             Malipayon nga pagsalin-urog han adlaw nga natawhan hiton pinakamahusay nga nanay ha bug-os nga kalibutan.

             Delete
             Replies

             Reply

             8
             *
             AnonymousJuly 13, 2021 at 12:46 AM

             Ano po sa waray ang "gusto ko lang din na malaman mo na ayokong mapunta ka sa iba"

             Delete
             Replies

             Reply

             9
             *
             UnknownSeptember 27, 2021 at 9:59 AM

             kung ang mukha ay bayhon,ang tsinelas ay ismagol ano naman sa tagalog ang dapi
             -dapi?

             Delete
             Replies

             Reply

             10
             *
             UnknownMarch 24, 2022 at 1:34 PM

             Anu po Ang waray Ng makata ?para po Kase sa school requirements (analysis using ninorte language)

             Delete
             Replies

             Reply

             11
             *
             AnonymousApril 27, 2022 at 8:39 AM

             Nagsumat haak.hi kuya jony kagab e

             Delete
             Replies

             Reply

             Reply

             2
             *
             AnonymousMarch 4, 2020 at 10:36 AM

             Ano po NANANALAYTAY sa Waray

             ReplyDelete
             Replies

             1
             *
             RhodoraMarch 7, 2020 at 11:53 AM

             Naabid. I just updated the list. Salamat. 😁

             Delete
             Replies

             Reply

             2
             *
             AnonymousJuly 13, 2021 at 12:48 AM

             Ano po sa waray ang "gusto ko lang din na malaman mo na ayokong mapunta ka sa iba"

             Delete
             Replies

             Reply

             3
             *
             UnknownSeptember 28, 2021 at 9:29 AM

             Pakitranslate po, di nalang ako magugulat pag pinagpalit ako sa mas matangkad

             Delete
             Replies

             Reply

             4
             *
             UnknownFebruary 1, 2022 at 7:43 AM

             Diak na mahihimangraw kun igsaliean muak sa mashataas

             Delete
             Replies

             Reply

             Reply

             3
             *
             UnknownMarch 14, 2020 at 10:22 PM

             anino= lambung (WS, Samar)

             ReplyDelete
             Replies

             1
             *
             RhodoraMarch 15, 2020 at 5:42 AM

             Salamat! Ak' na igindugang.

             Delete
             Replies

             Reply

             2
             *
             AnonymousFebruary 3, 2021 at 4:47 PM

             Ano po yung tumawa sa waray?

             Delete
             Replies

             Reply

             3
             *
             AnonymousMay 29, 2021 at 11:50 AM

             Tumawa - magtawa, magkatatawa

             Delete
             Replies

             Reply

             Reply

             4
             *
             UnknownMarch 30, 2020 at 5:47 PM

             Heyay! Kala huyo lugod , ano po ibig sabihin nito?

             ReplyDelete
             Replies

             1
             *
             AnonymousMay 15, 2020 at 6:34 AM

             Naku! Tumahimik ka na lang.

             Huyo - tumahimik

             Delete
             Replies

             Reply

             2
             *
             UnknownOctober 20, 2021 at 7:53 PM

             ano po ibig sabihin ng amo la ghap

             Delete
             Replies

             Reply

             3
             *
             AnonymousOctober 20, 2021 at 7:55 PM

             ano po ang ibig sabihin ng amo lagap

             Delete
             Replies

             Reply

             4
             *
             AnonymousJanuary 4, 2022 at 2:59 PM

             ganon pa rin
             "amo la gihap' 'nam' sura"
             "ganon pa rin ung ulam namin" or literal "ganon pa rin ang aming ulam"

             Delete
             Replies

             Reply

             Reply

             5
             *
             UnknownMay 1, 2020 at 11:47 AM

             Bagong bayani ng ating bayan patranslate po

             ReplyDelete
             Replies

             1
             *
             AnonymousMay 15, 2020 at 6:36 AM

             Bag-o nga bayani hit aton bungto.

             Delete
             Replies

             Reply

             Reply

             6
             *
             kgrnMay 5, 2020 at 1:17 PM

             ano po ang "Lipad" sa waray? salamat po

             ReplyDelete
             Replies

             1
             *
             AnonymousMay 15, 2020 at 6:37 AM

             lupad

             Delete
             Replies

             Reply

             Reply

             7
             *
             AnonymousJune 10, 2020 at 9:59 PM

             Ano po yung birat k sa waray?

             ReplyDelete
             Replies

             1
             *
             AnonymousAugust 13, 2020 at 4:34 PM

             ari ng babae

             Delete
             Replies

             Reply

             Reply

             8
             *
             AnonymousAugust 4, 2020 at 2:16 AM

             Daan - Agi (ES)
             Daanan - Aragian (ES)

             ReplyDelete
             Replies

             Reply

             9
             *
             Love KylaAugust 16, 2020 at 1:09 AM

             I'm Waray and I approve! Haha. Hinay pirme! :)

ReplyDelete
Replies

Reply

10
*
AnonymousAugust 18, 2020 at 12:55 PM

Ano po yun INUSIGAN sa waray?
Thank u po

ReplyDelete
Replies

1
*
AnonymousFebruary 10, 2021 at 6:08 PM

Inusigan=tinaholan
usig = tahol

Delete
Replies

Reply

Reply

11
*
JmAugust 25, 2020 at 7:06 PM

Anu po yung arog?

ReplyDelete
Replies

1
*
AnonymousJanuary 17, 2021 at 6:02 PM

Arog = matanda

Delete
Replies

Reply

Reply

12
*
UnknownOctober 9, 2020 at 8:23 PM

Ano po sa waray yung.

Sana sanabi mo agad. Para di nko umasa.

ReplyDelete
Replies

1
*
kohakuJanuary 17, 2021 at 5:41 PM

Unta gin-yakan mo dayon. Para waray na ako nag-laum.

Delete
Replies

Reply

Reply

13
*
UnknownOctober 15, 2020 at 12:57 PM

Sanggol sa waray

ReplyDelete
Replies

1
*
AnonymousFebruary 11, 2021 at 5:56 PM

Minasus-an.

Delete
Replies

Reply

Reply

14
*
UnknownOctober 16, 2020 at 5:18 PM

ano po sa waray ang kultura at paglalahad?

ReplyDelete
Replies

1
*
AnonymousFebruary 11, 2021 at 5:50 PM

Kultura = kultura
Paglalahad = paglaygay

Delete
Replies

Reply

2
*
UnknownJuly 19, 2021 at 9:44 PM

Haim bugto

Delete
Replies

Reply

Reply

15
*
UnknownOctober 22, 2020 at 7:32 PM

How about an TADHANA in tagalog?

ReplyDelete
Replies

1
*
AnonymousJanuary 29, 2021 at 3:43 PM

TADHANA tagalog yan

Delete
Replies

Reply

2
*
UnknownMay 16, 2021 at 12:26 PM

ahahahaaahahahahahaaha

Delete
Replies

Reply

Reply

16
*
UnknownNovember 9, 2020 at 10:08 PM

Anu po yung" matumba man ako ay inaalalayan sa waray

 ReplyDelete
 Replies

 1
*
 AnonymousFebruary 11, 2021 at 5:51 PM

 Matumba man ak, gin-aalalayan.

 Delete
 Replies

 Reply

 Reply

17
*
 UnknownDecember 1, 2020 at 10:43 PM

 Hi po. Ano po yung waray. Ng "TUNTUNIN" salamat

 ReplyDelete
 Replies

 1
*
 AnonymousFebruary 11, 2021 at 5:54 PM

 Batas lang ang alam ko.

 Batas = balaud/balaod.

 Sana may ibang makasagot.

 Delete
 Replies

 Reply

 2
*
 AnonymousJanuary 23, 2022 at 7:29 AM

 Subayon

 Delete
 Replies

 Reply

 3
*
 AnonymousJanuary 23, 2022 at 7:29 AM

 Subayon

 Delete
 Replies

 Reply

 Reply

18
*
 UnknownDecember 4, 2020 at 11:19 PM

 Ano po Yung pag-asa sa waray?

 ReplyDelete
 Replies

 1
*
 AnonymousJanuary 17, 2021 at 6:01 PM

 Paglaum/paglaom

 Delete
 Replies

 Reply

 Reply

19
*
 UnknownDecember 5, 2020 at 1:48 PM

 Kure manla kay wry koman jowa pa translate po sa tagalog

 ReplyDelete
 Replies

 1
*
 AnonymousJanuary 17, 2021 at 6:00 PM

 Ang hirap kasi wala akong jowa.

 Delete
 Replies

 Reply

 Reply

20
*
 UnknownDecember 30, 2020 at 12:26 AM

 ano po sa waray ang atod

 ReplyDelete
 Replies

 1
*
 AnonymousJanuary 17, 2021 at 5:59 PM

 Atod = pinsan

 Delete
 Replies

 Reply

 Reply

21
*
 UnknownJanuary 16, 2021 at 11:58 PM

 Ano po sa waray ang "nakasaing" o "saing"?

 ReplyDelete
 Replies

 1
*
 kohakuJanuary 17, 2021 at 5:40 PM

 Nakasaing = Nakatuon
 Saing = Tuon

 Delete
 Replies

 Reply

 Reply

22
*
 lalatjoJanuary 20, 2021 at 6:12 AM

 Talino and husay po sa waray?

 ReplyDelete
 Replies

 1
*
 AnonymousFebruary 11, 2021 at 5:44 PM

 Talino = kabaltok
 Husay = kamakarit

 Delete
 Replies

 Reply

 2
*
 UnknownApril 10, 2021 at 2:52 PM

 English: Reference
 Tagalog: Sanggunian
 Waray: ano po dawla? Pabulig man po salamat.

 Delete
 Replies

 Reply

 3
*
 AnonymousMay 16, 2021 at 11:34 PM

 Taramdan

 Delete
 Replies

 Reply

 4
*
 AnonymousSeptember 27, 2021 at 9:29 PM

 Use this in a waray sentence: "crush". At ano din ang waray ng crush.

 Delete
 Replies

 Reply

 Reply

23
*
 UnknownJanuary 29, 2021 at 3:40 PM

 nano sa tagalog ine nga "hi pikoy ngan an padi by severino caindoy"

 ReplyDelete
 Replies

 Reply

24
*
 UnknownFebruary 8, 2021 at 9:15 AM

 inga hatik imos imos gud man gin anano ko daw la siya

 pakitranslate po

 ReplyDelete
 Replies

 1
*
 AnonymousFebruary 11, 2021 at 5:45 PM

 Itong hatik baliw yata. Ano bang ginawa ko sa kanya?

 Delete
 Replies

 Reply

 Reply

25
*
 tineFebruary 20, 2021 at 12:46 AM

 ano po meaning ng maupdan??

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 8, 2021 at 3:24 AM

 Masamahan

 Delete
 Replies

 Reply

 Reply

26
*
 AnonymousFebruary 28, 2021 at 6:42 PM

 Ano po sa tagalog ang Puruko?

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 8, 2021 at 3:26 AM

 Maupo.

 Pero sa N.Samar, pwede itong "Tumigil ka."

 Delete
 Replies

 Reply

 Reply

27
*
 NhinzMarch 2, 2021 at 11:46 PM

 Ano po sa tagalog yung nakatuyaw?

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 8, 2021 at 3:32 AM

 Nakabulabog.

 Delete
 Replies

 Reply

 2
*
 UnknownMarch 18, 2021 at 11:31 AM

 Anu po SA waray ang
 Matanda kana mag bago kna

 Delete
 Replies

 Reply

 3
*
 AnonymousMay 16, 2021 at 11:35 PM

 Lagas ka na. Pagbag-o na.

 Delete
 Replies

 Reply

 4
*
 aesthetically_beeSeptember 14, 2021 at 11:44 AM

 nakatuyaw = istorbo

 Delete
 Replies

 Reply

 Reply

28
*
 AnonymousMarch 5, 2021 at 1:54 PM

 Ano.po sa tagalog ito -
 dikan dad a sa data panguha kam silot

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 8, 2021 at 3:31 AM

 Tapos dalhin sa data, kumuha kayo ng buko. (Data - baka farm po ito. Di ko alam ang word na ito. Sana may
 makabasa.)

 Delete
 Replies

 Reply

 Reply

29
*
 AnonymousMarch 18, 2021 at 10:17 AM

 ano po sa waray ang (palaging sinasabing magaral ng mabuti para sa hulit hangangan ay hindi ka magsisisi)

 yung totoo po sana for music cause thankyou po!!

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 22, 2021 at 11:14 PM

 Pirme iginsasagdon nga maniguro hin pag-eskwela basi diri magbasol ha kaurhian.

 Delete
 Replies

 Reply

 Reply

30
*
 AnonymousMarch 18, 2021 at 6:40 PM

 Ano po sa tagalog ang lanturon

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 22, 2021 at 11:11 PM

 Iluto (ang ulam) na may gata.

 Delete
 Replies

 Reply

 Reply

31
*
 Waray upayMarch 21, 2021 at 3:32 PM

 Anay is wait

 ReplyDelete
 Replies

 1
*
 UnknownApril 15, 2021 at 4:06 PM

 Ay mun-a

 Delete
 Replies

 Reply

 Reply

32
*
 UnknownMarch 23, 2021 at 12:55 PM

 Ano po ang intoy at iday sa waray

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 24, 2021 at 2:01 AM

 Intoy - totoy (batang lalaki)
 Iday - nene (batang babae)

 Delete
 Replies

 Reply

 Reply

33
*
 MarimarMarch 25, 2021 at 11:06 PM

 Ano po sa tagalog yung libakun ?

 ReplyDelete
 Replies

 1
*
 AnonymousMarch 27, 2021 at 11:24 AM

 Pagtsismisan.

 Delete
 Replies

 Reply

 Reply

34
*
 GlaizaApril 6, 2021 at 7:05 PM

 Tinatangi
 2. Kayang- kaya mo 'yan!
 3. Maganda Araw
 4. Panghabambuhay
 5.Talong
 ano po ito sa waray?

 ReplyDelete
 Replies

 1
*
 AnonymousMay 16, 2021 at 11:39 PM

 1. Hinigugma
 2. Kaya mo iton!
 3. Maupay nga adlaw.
 4.
 5. Taron

 Delete
 Replies

 Reply

 Reply

35
*
 UnknownApril 6, 2021 at 11:16 PM

 Ano sa tagalog ang "nadire ada haak it kalibutan"

 ReplyDelete
 Replies

 1
*
 AnonymousApril 28, 2021 at 11:54 PM

 Ayaw ata sa 'kin ng mundo.

 Delete
 Replies

 Reply

 2
*
 AnonymousMay 16, 2021 at 11:40 PM

 Baka ayaw sa akin ng mundo.

 Delete
 Replies

 Reply

 Reply

36
*
 AnonymousApril 26, 2021 at 4:24 PM

 ano s tagalog ang tapad

 ReplyDelete
 Replies

 1
*
 AnonymousMay 16, 2021 at 11:40 PM

 Katabi.

 Delete
 Replies

 Reply

 Reply

37
*
 AnonymousApril 30, 2021 at 10:09 PM

 Ano po sa waray ang Namimiskita. Salamat po

 ReplyDelete
 Replies

 1
*
 AnonymousMay 16, 2021 at 11:41 PM

 Minimingaw ako ha imo.

 Delete
 Replies

 Reply

 Reply

38
*
 AnonymousMay 2, 2021 at 2:58 PM

 Ano po sa waray yung ‘sorry’?

 ReplyDelete
 Replies

 1
*
 AnonymousJune 11, 2021 at 8:51 AM

 Pasayloa.

 Delete
 Replies

 Reply

 Reply

39
*
 AnonymousMay 14, 2021 at 12:48 PM

 Ano po sa tagalog ito "mabagsak kit sini pagpinansuhay"?

 ReplyDelete
 Replies

 1
*
 AnonymousMay 16, 2021 at 11:47 PM

 Babagsak tayo nang dahil sa pagsaway (sa mga bata). Pagpinansuhay po meaning yung pinapagalitan natin ang
 mga batang malilikot.

 Delete
 Replies

 Reply

 Reply

40
*
 AnonymousMay 16, 2021 at 10:53 PM

 Ano po sa waray ang "Balik ka na sa akin" 😂

 ReplyDelete
 Replies

 1
*
 AnonymousMay 16, 2021 at 11:48 PM

 Balik na ha akon.

 Delete
 Replies

 Reply

 Reply

41
*
 AnonymousMay 20, 2021 at 6:31 AM

 Ano po sa waray ito "pangarap ko sana balang-araw ay maging guro kita,kaso pasaway nga ako kaya malabong
mangyari"?

 ReplyDelete
 Replies

 1
*
 AnonymousJune 10, 2021 at 10:57 PM

 Gusto ko magin mag turutdo ko ikaw, pero kay malabad man ako amo bagat makuri mahitabo.

 Delete
 Replies

 Reply

 Reply

42
*
 AnonymousMay 20, 2021 at 12:07 PM

 Anu po it winaray hit color?

 ReplyDelete
 Replies

 Reply

43
*
 AnonymousMay 20, 2021 at 12:16 PM

 Color po sa waray

 ReplyDelete
 Replies

 1
*
 AnonymousJune 11, 2021 at 8:52 AM

 Kolor.

 Delete
 Replies

 Reply

 Reply

44
*
 AnonymousMay 21, 2021 at 8:16 AM

 Ano po sa waray ang "mahal na mahal ka namin tandaan mo yan"?

 ReplyDelete
 Replies

 1
*
 AnonymousJune 10, 2021 at 10:59 PM

 Gin hihigugma ka namon, ayaw eton kalimti.

 Delete
 Replies

 Reply

 Reply

45
*
 AnonymousMay 22, 2021 at 2:52 PM

 Ano po sa Waray ang pandemya, kopra, minahan, banwa, suhay, taal? Thank you po

 ReplyDelete
 Replies

 1
*
 AnonymousJune 11, 2021 at 8:57 AM

 Pandemya, lukad, minahan, banwa, suhay,.....di ko po alam ang taal.

 Delete
 Replies

 Reply

 Reply

46
*
 UnknownJune 8, 2021 at 10:29 PM

 Pa tranlate nga po sa Waray para sa Exam lng po...

 Tayo, tanging apat na letra para lang mabuo,
 Ano nga ba tayo?
 Teka wala nga palang tayo ang meron lang ay ikaw at ako.
 Sa pagbuhat ng sako ang aking nararamdaman,
 Di ko alam kung ano ang dahilan,
 Ang tanging nais ko lang ay malaman,
 Kung ikaw bay sa akin ay may pagtingin o nararamdaman.
 Ang tanging nais ko lang ay pasayahin ka,
 Ang tanging nais ko lang ay mahalin ka,
 Ang tanging nais ko lang lumigaya ka,
 Ngunit yun ay sa piling ko hindi sa piling niya
 May mas sasakit pa ba pag nakikita mo ang mahal mo na napapasaya na ng iba?,
 Yung nais mo na iba na ang gumagawa para sa kanya,
 At sabay silang sumasabay sa awit ng musika,
 Na para bang walang ako! oo nga pala walang “tayo".
Pasensya kana kung masyado akong feeling,
Feeling na halos malapit na sa pag ka assuming,
Bakit ka ba kasi nag pakita ng motibo gayong
ayaw mo naman pala makasakit ng tao?,
Siguro kasalanan ko masyado akong umaasa sa matatamis na salitang tuwing binibitawan mo ay kinikilig na ako
May naka pag sabi sa akin na kailangan mong humingi ng tawad sa taong nasaktan o nagawan mo ng kasalanan,
Ngayon nais kong humingi ng kapatawaran,
Dahil ang tanging nais ko lang naman ay masuklian,
Ang pag mamahal ko sa'yo na kahit kailan wala kang pag kakakilanlan.
Ngayon humihingi ako ng tawad,
Patawarin mo ako sa aking pag luha kahit WALANG TAYO,
Patawarin mo ako sa pananatili sa tabi mo kahit WALANG TAYO,
Patawarin mo ako sa pagpili ko sayo kahit WALANG TAYO,
Patawarin mo ako sa aking pag kapit kahit WALANG TAYO.
Patawarin mo ako sa hindi ko pag layo kahit WALANG TAYO
Patawarin mo ako sa hindi ko pag suko kahit WALANG TAYO,
Patawarin mo ako sa aking pag mamahal sa iyo kahit WALANG TAYO.
Mahal! patawarin mo ako,
Patawarin mo ako nang matapos na ang tulang ito,
Dahil na papagod na napapagod at nadudurog na nadudurog ako,
Sa bawat pag sambit ng katagang “WALANG TAYO".

 ReplyDelete
 Replies

 1
*
 AnonymousJune 11, 2021 at 8:55 AM

 Ang haba naman nito. Dapat may bayad na po. Haha! Peace!✌

 Delete
 Replies

 Reply

 Reply

47
*
 UnknownJune 9, 2021 at 11:33 AM

 Ano po yong nagpapasibo sa filipino?

 ReplyDelete
 Replies

 1
*
 AnonymousJune 11, 2021 at 8:53 AM

 Nag-uunahan.

 Delete
 Replies

 Reply

 Reply

48
*
 UnknownJune 16, 2021 at 10:42 AM

 nadadayunan gud ak tiaw kan ladin sadto nga ubayan ko sya sa pagiging single para di sya masad haha

 Pa translate Naman PO sa Tagalog plss

 ReplyDelete
 Replies

 Reply

49
*
 UnknownJune 16, 2021 at 10:44 AM

 nadadayunan gud ak tiaw kan ladin sadto nga ubayan ko sya sa pagiging single para di sya masad haha

 Pa translate Naman PO plzzz

 ReplyDelete
 Replies

 Reply

50
*
 AnonymousJune 17, 2021 at 1:49 AM

 Natuluyan talaga ang biro ko kay Ladin noon na samahan ko siya sa pagiging single para hindi siya malungkot. Haha.

 ReplyDelete
 Replies

 Reply

51
*
 UnknownJune 18, 2021 at 10:58 PM

 Ano po ang "kapangyarihan sa waray"?

 ReplyDelete
 Replies

 1
*
 AnonymousJune 19, 2021 at 5:06 AM

 Kangyarihan is gahum in Waray.

 Delete
 Replies

 Reply

 Reply

52
*
 UnknownJune 19, 2021 at 6:28 AM

 ano po ang "palagi kayo mag ingat jan"

 ReplyDelete
 Replies

 Reply

53
*
 UnknownJune 19, 2021 at 6:30 AM

 ano po ang "saan kayo naligo? saan si baby Bryce wala sya sa picture.? mag ingat kayo palagi"

 ReplyDelete
 Replies

 Reply

54
*
 AnonymousJune 29, 2021 at 8:25 AM

 Hi ano po yung “manginano”, “paimod”, and “kunta bagaw” in Waray?

 ReplyDelete
 Replies

 1
*
 AnonymousJuly 12, 2021 at 3:04 AM

 Paimod... patingin
 Kunta bagaw...sana sabi

 Delete
 Replies

 Reply

 Reply

55
*
 UnknownJuly 5, 2021 at 3:56 PM

 pa translate to tagalog please - upay pa iba na tawo, hays hain daw laak hini yana mangungutang waray man
 madaupan

 ReplyDelete
 Replies

 1
*
 AnonymousJuly 12, 2021 at 2:57 AM

 Mabuti pa ang ibang tao. Hays, saan kaya ako mangungutang ngayon. Walang malapitan.

 Delete
 Replies

 Reply

 Reply

56
*
 UnknownJuly 6, 2021 at 7:05 PM

 Ano pong ang kasingkahulugan ng malamrag, malipayon at salapian sa waray po?

 ReplyDelete
 Replies

 Reply

57
*
 UnknownJuly 13, 2021 at 1:06 PM

 ano po yung meaning ng talo kit..

 ReplyDelete
 Replies

 Reply

58
*
 UnknownJuly 20, 2021 at 9:31 AM

 Ano po 'yung "bakal" at "batas" sa Waray?

 ReplyDelete
 Replies

 Reply

59
*
 UnknownJuly 30, 2021 at 11:09 AM

 Pa transalate po ako sa waray

 Wala pa kaming sobra magpadala nalang ako pag nakapag tabi ako ng tip ko

 ReplyDelete
 Replies

 Reply

60
*
 AnonymousAugust 1, 2021 at 5:13 PM

 ano po yung tagalog ng kasuob po? di kopo mahanap pero meron ako nabasa kanina. salamat po.

 ReplyDelete
 Replies

 1
*
 AnonymousAugust 2, 2021 at 12:53 AM

 Kasuob? Baka kasuol po. Kasuol - ang sakit.

 Delete
 Replies

 Reply

 Reply

61
*
 MhyAugust 4, 2021 at 8:54 PM

 big help for me thanks

 ReplyDelete
 Replies

 Reply

62
*
 AnonymousAugust 5, 2021 at 12:09 PM

 Sibol bangin ngay po sa tagalog?

 ReplyDelete
 Replies

 Reply

63
*
 UnknownAugust 17, 2021 at 11:02 AM

 Ano po un isang wikang bisaya na tinatawag ring waray waray. Pangunahing wika ng silangang Visayas partikular sa
 buong pull ng Samar hilagang-silangang Leyte at ilang bahagi ng biliran. Sinasalita sa lungsod ng tacloban

 ReplyDelete
 Replies

 Reply

64
*
 AnonymousAugust 17, 2021 at 12:59 PM

 Pa translate po: Diak siton nakila. salamat po

 ReplyDelete
 Replies

 Reply

65
*
 JuanAugust 17, 2021 at 12:59 PM

 ano po ang "diak siton nakila" sa tagalog?

 ReplyDelete
 Replies

 Reply

66
*
 UnknownAugust 18, 2021 at 10:52 PM

 Pakitranslate po... 'Ikaw gudla'

 ReplyDelete
 Replies

 Reply

67
*
 AnonymousAugust 26, 2021 at 9:59 AM

 Ano pa ung "uli na" sa tagalog?

 ReplyDelete
 Replies

 1
*
 UnknownSeptember 27, 2021 at 1:55 PM

 Uwi na

 Delete
 Replies

 Reply

 Reply

68
*
 AnonymousAugust 26, 2021 at 11:11 PM

 ano po ang translation po ng "mahal ko ang aking wika" in waray po. salamat po.

 ReplyDelete
 Replies

 Reply

69
*
 UnknownAugust 30, 2021 at 8:04 PM

 Hi,pwede Po pa translate sa waray.😁
 Wala Akong pake alam kahit Anong Sabihin mo,Basta kami masaya kami sa Buhay namen,Hindi katulad mo na
 nabubuhay sa galet at sama ng loob. Salamat Po in advance. More blog pa Po about sa waray language please.

 ReplyDelete
 Replies

 1
*
 AnonymousSeptember 19, 2021 at 8:17 PM

 Waray ko labot kun ano't sisidngon nimo, basta kami malipayon kami hiton among kinabuhi. Di pareho ha imo nga
 nabubuhi ha kasina ngan pagdumot.

 Delete
 Replies

 Reply

 Reply

70
*
 UnknownSeptember 3, 2021 at 12:29 AM

 Kayy unta nag tuturoy kala anay hn mag Aalaga nga iba h iyu??

 ReplyDelete
 Replies

 Reply

71
*
 UnknownSeptember 4, 2021 at 12:33 AM

 tagalog ng egwalado ?

 ReplyDelete
 Replies

 1
*
 AnonymousSeptember 19, 2021 at 8:15 PM

 Suplado po.

 Delete
 Replies

 Reply

 Reply

72
*
 RaymartSeptember 7, 2021 at 8:38 PM

 ano po yung "pasaka" at nairapa" in tagalog?

ReplyDelete
Replies

1
*
AnonymousSeptember 19, 2021 at 8:14 PM

Pasaka is paakyat. Nairapa, yung hindi maganda ang tubo. Halimbawa po tanim.

Delete
Replies

Reply

Reply

73
*
UnknownSeptember 14, 2021 at 10:43 PM

Anu po waray nito? Buti nga Sinabi ko sayo atleast Alam mo, last na Lang to sa ngayon update kita ulit..

ReplyDelete
Replies

1
*
AnonymousSeptember 19, 2021 at 8:18 PM

Maupay ngani kay ginsidngan ko ikaw. At least maaram ka. Last na la ini ha yana.

Delete
Replies

Reply

Reply

74
*
AnonymousSeptember 21, 2021 at 11:23 PM

ano po yung "naruruyag"?

ReplyDelete
Replies

1
*
UnknownDecember 16, 2021 at 1:28 PM

nag kagusto o gusto

Delete
Replies

Reply

Reply

75
*
UnknownSeptember 30, 2021 at 5:59 PM

Anu po yung waray ng makatuwirang?

ReplyDelete
Replies

Reply

76
*
AnonymousOctober 3, 2021 at 3:33 PM

Ano po ibig sabhin ng warai bilak sa warai po??

ReplyDelete
Replies

Reply

77
*
UnknownOctober 5, 2021 at 9:14 PM

ano po sa waray ang bonding sa isat isa at samahan at pananampalataya?

ReplyDelete
Replies

Reply

78
*
Mathemathecal Function of MS AccessOctober 9, 2021 at 7:41 PM

ano po yung bayan sa waray?

ReplyDelete
Replies

1
*
UnknownDecember 16, 2021 at 1:27 PM

baryo

Delete
Replies

Reply

Reply

79
*
AnonymousOctober 14, 2021 at 4:25 PM

Ano po sa waray ang "buti nga sayo"

ReplyDelete
Replies

Reply

80
*
UnknownOctober 20, 2021 at 11:00 PM

Ano po sa waray ang "Nakalimutan ko na mag diverse in waray since I left my father's hometown 21 yrs. ago" sana po
masagot 🥰

ReplyDelete
Replies

Reply

81
*
UnknownOctober 20, 2021 at 11:03 PM

Ano nga po sa waray ang : Nakqlimutan ko na mag diverse in waray kasi I left my father's hometown 22 yrs. ago at
tsaka i was 3 yrs old back then. Salamat po sa maka translate.

ReplyDelete
Replies

Reply

82
*
UnknownOctober 20, 2021 at 11:04 PM

Ano nga po sa waray ang : Nakqlimutan ko na mag diverse in waray kasi I left my father's hometown 22 yrs. ago at
tsaka i was 3 yrs old back then. Salamat po sa maka translate.

ReplyDelete
Replies

Reply

83
*
AnonymousOctober 23, 2021 at 4:56 PM

hi!! ano pong ibig sabihin ng salitang "sugad" sa tagalog

ReplyDelete
Replies

1
*
UnknownDecember 16, 2021 at 1:26 PM

ganyan

Delete
Replies

Reply

Reply

84
*
AnonymousNovember 6, 2021 at 6:17 PM

ano po sa tagalog ang pagsisiring?

ReplyDelete
Replies

1
*
UnknownDecember 16, 2021 at 1:25 PM

mag sabi o sabihin

Delete
Replies

Reply

Reply

85
*
UnknownNovember 6, 2021 at 9:39 PM

Hello po pa traslate po in tagalog.

An Unsa nga kag anak in diri harumamay
tikang han katikangan in waray pahumay
Ngatanan bubuhaton para la magmaupay
pagtimagno han ira mga anak nga uray

ReplyDelete
Replies

Reply

86
*
AnonymousNovember 7, 2021 at 7:21 PM

ano po ang tagalog ng pagsisiring? Thank you in advance

ReplyDelete
Replies

Reply

87
*
JuanNovember 25, 2021 at 8:50 PM

Ak asawa nala an madiri

ReplyDelete
Replies

1
*
UnknownDecember 16, 2021 at 1:25 PM

asawa ko nalang ang ayaw

Delete
Replies

Reply

Reply

88
*
AnonymousNovember 27, 2021 at 3:25 PM

Hi ano po translation nito? Oo kay pati ak asawa gitalohi liwat

ReplyDelete
Replies

Reply

89
*
AnonymousNovember 29, 2021 at 10:49 PM

Ano yung tuyaw kamo

ReplyDelete
Replies

Reply

90
*
AnonymousDecember 16, 2021 at 12:02 PM

Translate in Waray "kamusta sitwasyon ng bagyo dyan? Update kayo"

ReplyDelete
Replies

Reply

91
*
UnknownDecember 18, 2021 at 9:44 PM

Basuni ko sa dughan
Diko ipatatanggal masking mangutngot
Afton gindultan
Kanilang magbilin, dagko na ulat basi tigaman
An magkalit na Palado,stay maghatag
Sin kasmdan
Punlay sin kapalaran
Pagtitipigan
Hinuduman

ReplyDelete
Replies

Reply

92
*
UnknownDecember 18, 2021 at 9:45 PM

Please po paki explain s tagalog po for quiz thank you po

ReplyDelete
Replies

Reply

93
*
AnonymousDecember 19, 2021 at 8:26 PM

Ptranslate po - Anuman katima naton kanda migay...iuuli tana ikaw..dina Kita makadto ha

ReplyDelete
Replies

Reply

94
*
AnonymousDecember 27, 2021 at 6:43 PM

Ano po ung "inaanes"?

ReplyDelete
Replies

Reply

95
*
AnonymousJanuary 16, 2022 at 1:10 PM

Hello !Ano po yung mga sandali(moments) sa waray?

ReplyDelete
Replies

Reply

96
*
UnknownJanuary 24, 2022 at 8:53 AM

Ano po yung "minsan nang" sa waray

ReplyDelete
Replies

Reply

97
*
UnknownJanuary 28, 2022 at 3:11 PM

Ano po sa waray yung mahal ka namin pa ingatan nyopo ang sarili nyo palagi

ReplyDelete
Replies

Reply

98
*
AnonymousJanuary 31, 2022 at 10:39 PM

Paki translate po,
"Mukha ka talagang pera kaya minamalas ka, sunod sunod na yan kamalasan mo ngayong taon dahil masama budhi
 mo. Demonyo ka!

 ReplyDelete
 Replies

 Reply

99
*
 AnonymousFebruary 2, 2022 at 5:31 AM

 Ano po yung meaning ng bagaw and kaber?

 ReplyDelete
 Replies

 Reply

100
*
 UnknownFebruary 13, 2022 at 12:27 PM

 Ano po sa waray yong "hirap din pala mag aral ng waray"

 ReplyDelete
 Replies

 1
*
 AnonymousMay 3, 2022 at 9:49 PM

 Bobo kalang

 Delete
 Replies

 Reply

 Reply

101
*
 UnknownFebruary 24, 2022 at 2:31 PM

 Patranslate please in waray, bakit anong nangyari sayo?. Pagaling ka. Thanks in advance

 ReplyDelete
 Replies

 Reply

102
*
 alex hagoriles jrMarch 7, 2022 at 8:24 PM

 ano po sa waray ang
 dali na bili tayo ulam

 ReplyDelete
 Replies

 Reply

103
*
 AnonymousMarch 21, 2022 at 11:43 PM

 makuri kay malabad hinduro diri nahuyo.
 pa translate po sa tagalo please may nag sabi po sakin eh diko po alam ang meaning

 ReplyDelete
 Replies

 Reply

104
*
 UnknownApril 2, 2022 at 9:07 PM

 Ano po yung supot iroy mahusay sa waray

 ReplyDelete
 Replies

 Reply

105
*
 UnknownApril 3, 2022 at 6:50 AM

 Ano po sa tagalog ang "gin bibiling" salamat

 ReplyDelete
 Replies

 Reply

106
*
 UnknownApril 8, 2022 at 7:29 PM

 Ano po sa waray ang "di ako manhid,pero nakikiramdam lang sa paligid" salamat po

 ReplyDelete
 Replies

 Reply

107
*
 AnonymousApril 12, 2022 at 1:43 AM

 Ano po ibig sabihin nito sa tagalog?
 "buyag man tim uyab doy. Mabusag liwat hiya ano?"

 ReplyDelete
 Replies

 Reply

108
*
 AnonymousApril 26, 2022 at 4:50 PM

 ano po ang pandemya sa waray?

 ReplyDelete
 Replies

 Reply

109
*
 AnonymousMay 3, 2022 at 3:19 AM

 Pa translate po sa waray " Pinagkakalat ni Arnold nung nag inuman sila sa bahay mo at nalasing sya ayaw raw syang
pauwiin at inakit raw sya ng asawa mo"

 ReplyDelete
 Replies

 Reply

110
*
 AnonymousMay 3, 2022 at 3:26 AM

 Ano po sa waray ang ( update kita next time) sana Po masagot

 ReplyDelete
 Replies

 Reply

111
*
 AnonymousMay 3, 2022 at 3:32 AM

 Ano po sa waray ang ( asawa mo kung umasta parang single )

 ReplyDelete
 Replies

 Reply

112
*
 AnonymousMay 3, 2022 at 6:13 AM

 Pa translate po sa waray (Update kita ulit pag may bago)

 ReplyDelete
 Replies

 Reply

113
*
 AnonymousMay 3, 2022 at 6:51 AM

 Pa translate po sa waray ( sabihan kita ulit pag may bago)

 ReplyDelete
 Replies

 Reply

Add comment
Load more...

Newer Post Older Post Home
Subscribe to: Post Comments (Atom)

For your translation needs, DM us.

* Blog Admin

Featured Post

An Mga Bandido (Selma Lagerlöf's The Outlaws in Waray) - Part 1

(An Mga Bandido was published in PAGLAUM: MGA EUROPEO NGA SUSUMATON HA WARAY [Hope, European Stories in
Waray] by the Ateneo de Naga Univers...

*

SEARCH THIS BLOG

              Search

THIS BLOG'S STATS

Popular Posts

*
*
 List of Waray Words: Tagalog to Waray
 Here's a list of Tagalog words and their Waray equivalent. I compiled this with the help of my fellow Waray friends. If
 there are errone...
*
*
 Your Online Waray Language Dictionary
 What is the Waray term for "tipsy"? What is the English word for " during "? This post will answer those questions. ...
*
*
 How Plural Ideas Are Expressed in Waray
 There are two ways of expressing plural ideas in the Waray language. The first one is easier -- you just add the word
 "mga" (ma-ng...
*
*
 Waray Sentences and Phrases and Greetings in Waray
 How do you say, "Good morning" or "Good afternoon" in Waray? Good morning is Maupay nga aga ; Good afternoon,
 Maupay...
*
*
 What's Your Google PageRank as of May 4, 2012?
 There has been a Google PageRank update very recently. It started several hours ago according to some webmasters.
 I'm happy with the o...
*
*
 Socialgo.com: No Longer A Free Webhosting Site
 Socialgo.com once hosted the two websites I made for my high school students. I liked it because of the many features
 that it offered to it...
*
*
 How to Say Good Morning, Good Afternoon, and Good Evening in Waray
 Hi everyone! This post is for those who want to learn how to say some greetings -- and to pronounce them correctly -- in
 the Waray language....
*
*
 Tagalog and Waray Sentences
 Here is a list of Tagalog sentences with their Waray translation. Just below the series of sentences, there is also a list of
 Waray sentence...
*
*
 Lyrics of Pikahi, Birahi, ngan Pakido-kido: A Waray Cha-Cha Song
 (Sung and Composed by Cristolo "Dodoy" Torres) I. Kaupay mo sumayaw Kayubay san im lawas Labi kun natalibong
 Ma...
*
*
 Cha-Cha Waray Medley (with lyrics)
 Youtube video courtesy of  MsSimplegirl1234 Maharaw nga Misay I. Kay ano ini nga gugma kon danay Mapawala,
 mapatuo usahay Pag-...

!->
BLOGS NG PINOY
DMCA.com
Protected by Copyscape Web Copyright Protection Software

 Contact Form  BLOG ARCHIVE

   * ►  2022 (1)
 Name
                                  * ►  October (1)

 Email *   * ►  2021 (4)

   * ►  August (1)
 Message *
                            * ►  July (2)

                            * ►  June (1)

                            * ▼  2020 (4)
 Send
   * ►  May (1)

   * ►  February (2)

   * ▼  January (1)

   * List of Waray Words: Tagalog to Waray

   * ►  2019 (3)

   * ►  December (3)

   * ►  2018 (2)

   * ►  January (2)

   * ►  2017 (6)

   * ►  September (2)

   * ►  July (4)

   * ►  2013 (17)

   * ►  December (1)

   * ►  October (2)

   * ►  July (1)

   * ►  June (2)

   * ►  May (1)

   * ►  April (2)

   * ►  March (2)

   * ►  February (1)

   * ►  January (5)

   * ►  2012 (27)

   * ►  December (1)

   * ►  October (1)

   * ►  August (2)

   * ►  July (3)

   * ►  June (2)

   * ►  May (2)

   * ►  April (2)

   * ►  March (2)

   * ►  February (9)

   * ►  January (3)

   * ►  2011 (27)

   * ►  November (1)

   * ►  September (2)

   * ►  August (4)

   * ►  July (3)

   * ►  June (4)

   * ►  May (7)

   * ►  April (3)

   * ►  March (1)

   * ►  February (1)

   * ►  January (1)

   * ►  2010 (1)

   * ►  December (1)
Copyright 2010-2022. Theme images by mammuth. Powered by Blogger.

