* 42 Useful Waray Words and Phrases to Learn for Travelers

ByJunjie Gabrinez February 20, 2024

As we all know, the Philippines has been a bastion of different culturally
rich local languages over the years. Filipinos never cease to amaze foreigners
and even locals over the fact that we don’t only speak Tagalog or English.
This phenomenon always manifests during one of the oldest essential activities
known to humans, traveling. Should you interest yourself in this endeavor,
learning Waray words and phrases would serve as a good foundation.

If you ever find yourself wandering around Visayas, you might want to take a
look at the Eastern Visayas region (Region VIII), which is composed of Leyte,
Southern Leyte, Samar, Northern Samar, Eastern Samar, and Biliran.

Tip: Explore Tacloban City on a half-day tour and use the Waray words and
phrases you learned here when interacting with the Waraynons. You can do it!

BOOK TACLOBAN CITY TOUR

Aside from being known for its wide variety of uncharted beaches and islands,
it encapsulates what the natives call “home” for them. Come to think of it,
the natives, mostly called as “Waray” or “Waraynon”, consider the region as
their “everything”, whereas the meaning of the word Waray is actually
“nothing”. This intricacy can serve as a kickstart for you to explore the
region.

As a Waraynon myself, allow me to help you learn some basic words or phrases
from the Eastern Visayas’ predominantly used local dialect, Waray.

Basic Waray words and phrases for introductions and greetings

Waray words and phrases will come in handy when crossing the San Juanico
Bridge

*  “Maupay nga aga!” = “Good day!”

Waraynons usually greet with “Maupay na adlaw” as a general acknowledgment.
Time-wise, you may also use these other options:

** Maupay nga aga – Good morning
** Maupay nga udto – Good noon
** Maupay nga kulop – Good afternoon
** Maupay nga gab-i – Good evening

*  “Ako hi <name>.” / “It akon ngaran kay <name>.” = “My name is <name>.”

When you try to let the person know what your name is, you can start with this
phrase.

*  “Ano it imo ngaran?” = “What is your name?”

If you inquire about others’ names, you may conveniently use an alternative
for “it imo”, which is “tim”. So, you can also ask, “Ano tim ngaran?”.

*  “Kamusta ka?” = “How are you?”

Every catch-up with someone must start with this phrase to ensure the
conversation goes well. Plus, it’s easy since you might probably have known
this phrase from the Tagalog language.

*  “Maupay man, salamat.” = “I’m fine, thank you.”

This is your reply if someone asks how you are.

*  “Taga-diin ka?” = “Where are you from?”

Inquiry of whereabouts is the most common gesture travelers do in every place
they explore.

*  “Ngayan?” = “For real?” / “Really?”

You may use this word if you want to express your amazement during a
conversation.

*  “Oo” = “Yes”

To add, if you want the affirmation to be obvious or as expected, you may add
“gad” (“Oo gad”) or convert “Oo” to “Alang”, for which it means “Of course!”.

*  “Dire” = “No”

Say “dire” if you want to decline something. If it’s temporary, you may say
“dire la anay yana”, which means “not yet for now”.

Useful Waray words and phrases for social etiquette

*  “Alayon” = “Please”

Since Filipinos are known for their hospitality, let’s acknowledge it with a
habit of saying “Please” in every favor or gesture we ask others to do.

*  “Damo nga salamat!” = “Thank you so much!”

Despite “salamat” being the most commonly known local word for “thank you”,
make it a custom to add a degree to your gratitude by saying “Damo nga
salamat!”.

*  “Paghirot!” = “Take care!”

Another Waray term for “take care” would also be “paghinay”, although it is
used more when you are trying to say “slow down” in Waray.

*  “Padayon!” = “Keep going!”

Aside from its other meanings like “come in” and “continue”, this Waray word
has been considered a word of affirmation in terms of promoting perseverance
for locals. You may close out a conversation with this short term to express
warmth and support.

*  “Wait for me” = “Hulta ak”

Other variations for this phrase would be, “Anay la” which translates to “Just
a minute”.

*  “Pasayloa ko!” = “I’m sorry!”

Same with Bisaya, Waray also has the term “Pasayloa ko” for expressing your
apologies.

*  “Nahihidlaw na ak ha imo.” = “I miss you.”

Say this Waray phrase if you miss the person.

Handy Waray phrases and terms for travel and exploration


*  “Hain dapit?” = “Where exactly?”

If you ever ask for a specific location or address, you may use “Hain”, which
refers to “Where”. This also applies to asking where a certain product is
found.

*  “Gin-aano pakadto ha <place>?” = “How to get to <place>?”

For navigation, this phrase would be handy in case you encounter people who
are familiar with local routes.

*  “Hain ako/kita mahaw-as?” = “Where should I/we get off?”

Assuming you would be commuting, this will be your question when you ask where
to drop-off.

*  “Pakain ini?” = “Where is this going?”

Say this Waray phrase if you ask for the destination or route, especially when
riding public transport.

*  “Pakadto kita ha <place>.” = “Let’s go to <place>.”

As people tend to be enthusiastic when asked if they are interested in going
somewhere, this would be the perfect response.

*  “Hirani/Harani na ako” = “I’m getting near”

Should you be meeting someone somewhere, you may update them with this phrase.
Otherwise, you may say “Hirayo pa ako”, which means “I’m still far”.

*  “Mauli na ako!” = “I’m going home!”

Aside from expressing your desire to go home, you may say “Malakat na ako”,
which means “I’ll get going”.

*  “Diri ak maaram / Ambot” = “I don’t know”

When asked about something you have no idea about, this is what you respond
with. If you are not sure about something, you may say, “Diri ak sigurado”,
which means “I’m not sure”.

*  “Tagpira it pasahe?” = “How much is the fare?”

While you are inside the jeep or bus, you may worry less about knowing the
fare by asking the price for it with this phrase.

*  “Lugar!” / “Para!” / “Didi la!” = “I’ll get off here!” / “I’ll stop here!”

If you want to notify the driver that you will be dropping off, you may say
this when that moment comes.

*  “Hain ka yana?” = “Where are you now?”

Should you want to communicate with a Waraynon acquaintance through text or in
person, you may start the conversation with this phrase, especially if you are
planning a meetup.

*  “Makain ka?” = “Where are you going?”

Use this when you ask a Waraynon local or friend about their next stop or
destination.

*  “Ano nga oras matikang?” = “What time does it start?”

If you want to attend a local event, you may use this phrase to inquire what
time the event starts.

*  “Kakan-o ka pa nakadi?” = “Since when have you been here?”

Waraynon locals tend to ask visitors or tourists about how long they have
stayed in the province or region. When someone asks you this, make sure to
familiarize the phrase above for you to come up with a response.

*  “Pwede ak umupod?” = “Can I come with you?”

Once Waraynons share their current plans, you may find yourself interested in
coming with them. You may politely ask them using this phrase.

Waray language words and phrases for shopping and buying


*  “Maupay!” = “Hello!”

Although this Waray word is mostly known for its meaning, which is “Good!”,
you can also utter this when calling the attention of the vendor, especially
when no one is there initially.

*  “Mapalit ak hini!” = “I’ll buy this one!”

Another variation of this statement is “Mapalit ak hito” (I’ll buy that one).
If you want to specify a product, you may just say, “Mapalit ak hin <product
name>” (I’ll buy <product name>).

*  “Ano ini?” / ”Ano iton?” = “What’s this?” / “What’s that?”

When inquiring about a product’s specifications, you may start your question
with this phrase.

*  “Tagpira?” = “How much?”

This Waray word is the general term for price inquiry. One can suffice it with
“inin” (this) or “iton” (that). For the total, you may say “Tagpira tanan?”
(How much is everything?).

Practical Waray phrases for food and eating

Use Waray words when buying Tacloban delicacies

*  “Marasa man ini!” = “This is delicious!”

When you want to commend a food you just ate or tasted, exclaiming with this
phrase is the best compliment for a Waraynon, especially if they are the ones
who prepared the food.

*  “Pangaon kita!” = “Let’s eat!”

This is usually used when the food is ready and you want to invite everyone
present.

*  “Pangadji / Pangadi kita” = “Let’s pray”

It’s a prevalent practice everywhere in the Philippines to pray for grace
before eating as a gesture of thanks. Use this when you intend to lead
everyone for a prayer before a meal.

*  “Mayda pa pagkaon / sud-an?” = “Are there more food?” / “Is there still
food available?”

Ask with this Waray-Waray phrase to know if there is still food available.

*  “Alayon ak hiton na <item>?” = “Can you please pass me the <item>?”

It is normal in every breakfast, lunch or dinner, especially if it’s a big
gathering, to politely ask something to be passed down, such as a platter of
rice, a bowl of soup, or utensils.

*  “Busog na ak!” = “I’m already full!”

It is guaranteed you’ll be asked by someone to eat more or if you want more
food. To politely decline this, you may just use this Waray-Waray phrase.

*  “Gusto ko ini tilawon!” = “I want to taste this!”

Exploring the place is not complete without exploring the food. If you want to
express your interest in tasting a local food, you may start with saying this
phrase.

Now that you know how to speak Waray, which ones on our basic Waray Waray
words list are easy to remember?

Connecting with the Waraynon locals has never been this easy and fun. Sooner
or later, you’ll find yourself immersed in the culture and wonders of
Waraynons.

Having a glimpse of the Eastern Visayas region will surely interest you to
explore Central Visayas and Western Visayas as well. With that, you might want
to learn Cebuano and Hiligaynon before you land at their respective airports
like Cebu airport. And be sure to indulge in local Cebuano delicacies
including lechon before leaving Cebu.

If you’re visiting Northern Luzon, pick up some Ilocano words and phrases.
When in Bicol, learn some basic Bicolano words. And, if you’re exploring
Mindanao, particularly Zamboanga City and Basilan, you may want to start
learning the Chavacano language.
